### ISSUE TITLE
Cannot read properties of null (reading 'shadowRoot') #84

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#1]
please see the original issue at Maykar's repo https://github.com/maykar/kiosk-mode/issues/84

will you be able to 'clone' these issues too? and, if yes, be willing to see what can be done to prevent this from happening?

Sincere hopes (and thanks btw!) you can maintain the repo, because it was too nice to not keep up with current Dashboard

```
2022-01-05 12:51:05 ERROR (MainThread) [frontend.js.latest.202112290] https://mydomain/local/lovelace/resources/kiosk-mode/kiosk-mode.js?v=1.2.1:13:44 Uncaught TypeError: Cannot read properties of null (reading 'shadowRoot')
```

keeps showing in the log, not exactly sure when or why any user action causes this.
please have a look?

**Comment by cedev-modexpeng** [comment]
I also have this popping up. I tried adding kiosk-mode to my config.yaml file but didn't change anything.

`2022-09-20 18:40:10.166 ERROR (MainThread) [frontend.js.latest.202208020] http://10.147.17.75:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:13:51 TypeError: null is not an object (evaluating 'e.shadowRoot.querySelector("hui-root").shadowRoot')`

**Comment by Mariusthvdb** [comment]
is this still happening? tbh, I dont see them anymore, so, if someone will confirm, we can close?

**Comment by elchininet** [comment]
Hey @Mariusthvdb,
I wanted to ask the same because I had something in mind if this was still happening.
Maybe it got solved with the latest changes that I did.
Let‘s left it open for some days to see if someone else responds, if not it can be closed.

**Comment by pklijzing** [comment]
I'm stil getting them.
`Logger: frontend.js.latest.202303091
Source: components/system_log/__init__.py:254 
First occurred: 10:22:47 (3 occurrences) 
Last logged: 10:23:10

http://192.168.178.66:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:43:65 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
http://192.168.178.66:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:1:5329 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
`

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
Could you check one more time if this error is showing for you in your logs?
Regards

**Comment by Mariusthvdb** [comment]
sure, as I said above, I dont see these anymore, but I've filtered the errors to 'fatal'

I'll restart using no filter and check again

**Comment by jamincollins** [comment]
I am seeing this error:
```
Aug 16 20:59:29 home-assistant hass[843]: 2023-08-16 20:59:29.136 ERROR (MainThread) [frontend.js.latest.202306080] https://domain_here/local/kiosk-mode.js:13:44 Uncaught TypeError: Cannot read properties of null (reading 'shadowRoot')
```
