### ISSUE TITLE
Moving between dashboard views does not scroll to the top

### ISSUE THREAD

**Issue by sigo** [NemesisRE/kiosk-mode#10]
I have a dashboard with several views. When I scroll to the bottom of the view and then go to another subpage, I am not at the top of that view. I am slightly shifted down.

The problem occurs regardless of the device. When I have the header turned off.

**Comment by elchininet** [comment]
Hi @sigo,
Could you confirm that this only happens if you have the `hide_header` option activated?
Here on my side, I have tried to reproduce what you describe but in my case it is the regular behaviour, it happens regardless having this plugin installed or not.
Regards.

**Comment by lenwar** [comment]
I have something that may be related to this. When I have `hide_header` on, I can scroll up further than my screen goes.
So even if my view is shorter than the height of my screen, if I scroll up, I ‘lose’ the top part of my view until I scroll down again.

i have this at least on iOS. I’ll double check on my desktop later today.

**Comment by elchininet** [comment]
Hi @lenwar,
That seems a different issue even if it is something related to scroll and the `hide_header` option, please, open a new one describing what you are mentioning here and stating the IOS version that you have to see if someone can reproduce it.
Regards.

**Comment by sigo** [comment]
> Hi @sigo,
> Could you confirm that this only happens if you have the `hide_header` option activated?
> Here on my side, I have tried to reproduce what you describe but in my case it is the regular behaviour, it happens regardless having this plugin installed or not.
> Regards.

@elchininet Yes, that's right. The problem occurs regardless of this add-on. However, it so happens that the standard bar (header) is attached to the top edge of the screen. One can always access it.

While the package itself does not create a bug here, having to scroll up the page to access your own navigation is a bit of a nuisance.

It's hard to know what to do about this fact.

**Comment by elchininet** [comment]
@sigo,

I wanted to update you when the plugin was published in HACS, but [it seems that it will take a while](https://github.com/hacs/default/pull/1810). For now, you can install it manually.

https://github.com/elchininet/lovelace-autoscroll

Regards
