### ISSUE TITLE
[BUG] local/kiosk-mode/kiosk-mode.js?v=1.7.2:57:87 TypeError: can't access property "querySelector", e is null

### ISSUE THREAD

**Issue by clowncracker** [NemesisRE/kiosk-mode#104]
**Describe the bug**
Every time I start Home Assistant, I get the following error:
http://xxx/local/kiosk-mode/kiosk-mode.js?v=1.7.2:57:87 TypeError: can't access property "querySelector", e is null

**To Reproduce**
I do not know why it thinks I'm using version 1.7.2, which is the old release from maykar.  I've uninstalled and reinistalled kiosk-mode multiple times and when I look at it in HACS, it shows version 3.0.0.  I've validated that config/www/community/kiosk-mode has the latest kiosk-mode.js.

**Versions:**
 - Home Assistant: 2023.8.1
 - Kiosk-Mode: 3.0.0

**Comment by elchininet** [comment]
Hi @clowncracker,
Could you enter in that link (`http://xxx/local/kiosk-mode/kiosk-mode.js?v=1.7.2`) in your machine, paste the content in a guist and share it with us, so we can check what is its content?
Regards

**Comment by elchininet** [comment]
[In a gist](https://gist.github.com/clowncracker), just to avoid pasting it here because it should be long.

**Comment by clowncracker** [comment]
Did you want me to type `http://xxx/local/kiosk-mode/kiosk-mode.js?v=1.7.2` in my web browser?

**Comment by elchininet** [comment]
Yes, replacing `xxx` by your ip or domain.

**Comment by clowncracker** [comment]
404: Not Found

**Comment by elchininet** [comment]
Open the developer console, and open this file:

![image](https://github.com/NemesisRE/kiosk-mode/assets/3728220/42af6d45-17a6-4af2-b83e-e3d96cdcebc5)

**Comment by elchininet** [comment]
Also, go to `your ip or domain/config/lovelace/resources` and paste the resources relatives to `kiosk-mode` that you have there.

**Comment by clowncracker** [comment]
I think the source of the problem is a rogue resource:

![image](https://github.com/NemesisRE/kiosk-mode/assets/49218426/79356d09-e029-4e09-9399-9c167218854f)

**Comment by elchininet** [comment]
That is my supicious, do you also have a `/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=xxxxx` one?

**Comment by clowncracker** [comment]
Yup.  Restarting my VM now to see if the error pops up again.

**Comment by elchininet** [comment]
Hi @clowncracker,
Did you check that you are not having the issue anymore?
Regards

**Comment by clowncracker** [comment]
@elchininet I believe we are good to go.  Iy was the rogue resource.
