### ISSUE TITLE
[BUG] kiosk mode does not appear to be fully removing the headers for mobile users

### ISSUE THREAD

**Issue by jamincollins** [NemesisRE/kiosk-mode#105]
**Describe the bug**
kiosk mode does not appear to be fully removing the headers for mobile users

**To Reproduce**
1. Using a mobile device (cellphone, tablet)
2. Log into Home Assistant as a non-admin user
3. Go to Dashboard in question

Alternative steps:
1. Using a mobile device (cellphone, tablet)
2. Log into Home Assistant as an admin user
3. Go to Dashboard in question
4. add `?kiosk` to URL

**Expected behavior**
Header and Sideboard are gone.

**Experienced behavior**
Header is still present with the burger menu to access the other parts of Home Assistant (dashboards, etc).

**Screenshots**
This is a normal, non-kiosk view of the dashboard:
![signal-2023-08-16-212315_003](https://github.com/NemesisRE/kiosk-mode/assets/1904577/9d8235b2-0afc-4b5b-9497-a1b4c3488ab1)
This is a view with `?kiosk` on the URL.
![signal-2023-08-16-212315_002](https://github.com/NemesisRE/kiosk-mode/assets/1904577/5ff8ec94-521c-41e5-906d-49546f71619e)
The only noticeable difference is that the weather card is shoved under the header.

**Versions:**
 - Home Assistant: 2023.8.2
 - Kiosk-Mode v3.0.0

**Additional context**

I've tested adding `?kiosk` to the URL on a normal PC browser and it appears to work as expected.

Top of dashboard YAML
```
title: Guest Suite
kiosk_mode:
  non_admin_settings:
    hide_header: true
    hide_sidebar: true
    kiosk: true
views:
```

**Comment by elchininet** [comment]
Hi @jamincollins,
First, let‘s solve [this](https://github.com/NemesisRE/kiosk-mode/issues/106) and then we can check if you are still getting the same about this issue.
Regards

**Comment by jamincollins** [comment]
Resolving the above (stale JS) did resolve this as well.
