### ISSUE TITLE
[FR] hide notifications entry

### ISSUE THREAD

**Issue by pkoevesdi** [NemesisRE/kiosk-mode#107]
My simple user using kiosk mode should not see or open any notifications.
Still I'd like to have the sidebar. Can a `hide_notification` be added?

**Comment by elchininet** [comment]
Hi @pkoevesdi,
I‘ll take a look at the code to check if your proposal can be achieved.
I‘ll let you know, leting this issue open until then.
Regards

**Comment by elchininet** [comment]
Hi @pkoevesdi,
After [this](https://github.com/NemesisRE/kiosk-mode/pull/109) gets merged and a new version of the library is released, this feature will be available in `kiosk-mode`.
Regards

**Comment by pkoevesdi** [comment]
Wow, that was fast, thank you soo much!
