### ISSUE TITLE
[BUG] hide_dialog_climate_actions doesn't work as intended with HA 2023.9.0

### ISSUE THREAD

**Issue by BoneheadFraggle** [NemesisRE/kiosk-mode#110]
**Describe the bug**
When using the `hide_dialog_climate_actions`, in HA 2023.9.0, the whole dialog is hidden.

**To Reproduce**
1. Try hide_dialog_climate_actions: true
2. Click on a climate entity
3. See error below

![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/7bf67ddc-549e-4c70-ac55-1a706a72e733)

**Expected behavior**
Not sure really. Optimally, I would like to show the current values, but without the ability to change them. 
But with the new dialog, I can't really see how to hide the actionable things.
Maybe the option should be depreciated. 

![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/65040a5d-558f-4623-93d9-f80df1b9f5bc)

**Versions:**
 - Home Assistant: [2023.9.0]
 - Kiosk-Mode [v3.1.0]

**Additional context**

**Comment by NemesisRE** [comment]
Hi,
that's exactly the expected behavior but in the old version of HA the more info dialog also showed current and target temp in a different div which was not hidden as you can see below 

![more-info-dialog-climate-entity](https://github.com/NemesisRE/kiosk-mode/blob/master/images/more-info-dialog-climate-entity.png)

**Comment by NemesisRE** [comment]
Maybe it is possible to enhance it by hiding the dial and the buttons below it but keep the current temp above the dial.

**Comment by elchininet** [comment]
I‘ll try to check what are the possibilities here, it is not even close to the previous climate.
Regards

**Comment by elchininet** [comment]
Hi @BoneheadFraggle,

This is my proposal, in line whith what @NemesisRE mentioned. You cannot interact with anything but you can see the values.

<img width="574" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/3728220/bfd6aed9-003a-4628-bfd7-c01267aafe76">

As usual, I would need that you test it on your side, install [the gist]
(https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) manually and let me know the result.

Regards

**Comment by BoneheadFraggle** [comment]
> Hi @BoneheadFraggle,
> 
> This is my proposal, in line whith what @NemesisRE mentioned. You cannot interact with anything but you can see the values.
> 
> <img alt="image" width="574" src="https://user-images.githubusercontent.com/3728220/266435908-bfd6aed9-003a-4628-bfd7-c01267aafe76.png">
> As usual, I would need that you test it on your side, install [the gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) manually and let me know the result.
> 
> Regards

Ok, that's much better than what I imagined. Still good looking, but safe from tinkering fingers.
Works like a charm.

Thanks!

**Comment by elchininet** [comment]
Perfect, thanks for testing.
I‘ll prepare the pull request.
Regards
