### ISSUE TITLE
[BUG] `Kiosk: true` & "Always hide the Sidebar" `on` can lock a mobile screen

### ISSUE THREAD

**Issue by RedNo7** [NemesisRE/kiosk-mode#112]
**Describe the bug**
Under the following circumstances:
- `kiosk: true`
- "Always hide the sidebar" set
- Using a mobile device
...if you try to slide the side menu out on a mobile device (as I do through muscle memory by accident), the screen dims and locks up.

...it's as if an invisible menu has actually slid out that prevents you from then selecting anything on the dashboard.  It is not possible to reverse the motion (slide the menu out of sight) to gain access back to the dashboard.  Only killing the app and restarting it gives control back,

 - Console log errors (F12)
no errors.

**To Reproduce**
1. Go to any dashboard on a mobile device with `kiosk: true` set and "Always hide the sidebar" set
2. Right-swipe from the LHS of the screen to try to slide out the side menu.  Of course, nothing should happen.
3. The screen dims and is now locked.

**Expected behavior**
Nothing should happen and the dashboard should remain functional.

**Screenshots**
Nothing. to see - the dashboard dims a little.

**Versions:**
 - Home Assistant: 2023.9.2 (but also reovirus versions)
 - Kiosk-Mode 4.0.0

**Additional context**
I assume there is some interference with Kiosk m ode and the "Always hide the sidebar" option on mobile devices.

The workaround is to disable "Always hide the sidebar".

**Comment by elchininet** [comment]
Hi @RedNo7,

That is a known issue, there is a clash between the native IOS App and kiosk mode. You can follow a similar discussion [here](https://github.com/NemesisRE/kiosk-mode/discussions/100#discussioncomment-6543821). We can hide HTML elements but we cannot ignore touch events from the native App or ignore what the front-end code does when it receives those events. Unfortunatelly, there is no much that we can do from our side at this moment, that would require some help from the app/front-end developers to see if we can do something to avoid that.

I am seeing that the [Discord discussion](https://discord.com/channels/330944238910963714/551871772484698112/1133733133829816412) that @Mariusthvdb started didn‘t receive too much attention.

Regards

**Comment by RedNo7** [comment]
got I t- thanks for explaining!

**Comment by elchininet** [comment]
@RedNo7 @Mariusthvdb, I need you both to test this because I don‘t have an IOS device. Could you uninstall `kiosk-mode` and do [a manual installation](https://github.com/NemesisRE/kiosk-mode#installation) of [the kiosk-mode guist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) and check if this issue is solved when the sidebar is hidden?
Regards

**Comment by RedNo7** [comment]
Sure - will try this tomorrow and let you know.

**Comment by Mariusthvdb** [comment]
@RedNo7 are you saying the manual install of @elchininet 's  gist fixed the issue, or, does it still behave like with the release version, not sure I read your post as it should..

**Comment by elchininet** [comment]
@Mariusthvdb,
I think that he says that he doesn‘t notice any difference between the manual installation and the one through HACS.

@RedNo7,
It would be good to know if you are not loading a cached version of the plugin. Did you add the hsh at the end of the resource URL and cleaned the cache of the App?

Regards

**Comment by RedNo7** [comment]
@Mariusthvdb - @elchininet is correct. I did not notice any difference between the manual install and the standard install.

When you write “did I add the hash at the end” are you referring to the version number? If so, yes, if not, I’m not sure what you mean.

**Comment by elchininet** [comment]
>When you write “did I add the hash at the end” are you referring to the version number?
Yes, the version or anything else, just to change the URL. The second things necessary in the App is to clean the cache, Apps have a strong caching system.
Regards

**Comment by elchininet** [comment]
Go to the sidebar, search for app configuration > debugging > reset frontend cache.

**Comment by RedNo7** [comment]
Ok, will try this again tomorrow and report back,

**Comment by RedNo7** [comment]
**WOW!**

That works perfectly!  **Thanks!** 👍 

I would love to understand why it needs a manual install though!

**Comment by elchininet** [comment]
@RedNo7,
It doesn‘t need a manual install per se. I just wanted to know if the workaround works, after knowing that it works I can create a pull request and it can be shipped in a new version.
Regards

@Mariusthvdb, it seems to work, just test it on your side to be double-sure.

**Comment by Mariusthvdb** [comment]
Finally gotten around to do so. let describe what happens and check if thats what you want it to do:

turn on 'hide sidebar' . On desktop the sidebar hides, on mobile nothing shows as there is no sidebar.
on mobile, try and slide in the menu from the left: nothing happens, screen solid as a rock. (before this is where the hang appeared)

turn off hide_sidebar once again, and all back to normal: Dekstop shows the sidebar, and mobile allows to slide it in nicely

**Comment by elchininet** [comment]
@Mariusthvdb,
Super, so it is working properly indeed. Workaround works.
I‘ll submit a pull request.
Regards
