### ISSUE TITLE
[BUG] Kiosk Mode Query Strings do not work for Ingress Pages

### ISSUE THREAD

**Issue by jgoakley** [NemesisRE/kiosk-mode#113]
**Describe the bug**
The Query Strings feature does not appear to work when using the Home Assistant OS ingress feature

**To Reproduce**
1. Install AddOn that supports ingress. Example: Grafana
2. Go to ingress url of addon and append ?kiosk to end of url. Example: http://[home-assistant-url]/a0d7b954_grafana/ingress?kiosk
3. Observe that header and sidebar do not disappear.

**Expected behavior**
The header and sidebar would disappear when appending query string

**Screenshots**
![image](https://github.com/NemesisRE/kiosk-mode/assets/9720393/ae82c62b-9219-415b-b4fa-0ba13d05b223)

**Versions:**
 - Home Assistant: [e.g. 2023.9.3]
 - Kiosk-Mode [e.g. v4.0.0]

**Additional context**
The kiosk-mode custom component appears to be correctly installed because when I append "?kiosk" to the main overview page (For example: https://home-assistant-url/lovelace/0?kiosk) it correctly hides the header and side bar.

**Comment by elchininet** [comment]
Hi @jgoakley,

As it is stated in the description of this plugin:

>Hides the header and/or sidebar drawer in Home Assistant **lovelace dashboards**.

This plugin is not intended to work in any other place but lovelace dashboards.

Regards

**Comment by jgoakley** [comment]
Thanks for the clarification!

And thank you for this great plugin!
