### ISSUE TITLE
[FR] Add-on repository?

### ISSUE THREAD

**Issue by Niek** [NemesisRE/kiosk-mode#114]
Thanks for this great project!

Would it be possible to make this available as a regular add-on to HA (without the need for HACS or a manual install)?

See:
* https://github.com/home-assistant/addons-example
* https://developers.home-assistant.io/docs/add-ons

**Comment by elchininet** [comment]
Hi @Niek,
This is not an add-on, it doesn‘t run in a separate Docker container as add-ons do. This is just a `JavaScript` file that should be registered as [a resource](https://developers.home-assistant.io/docs/frontend/custom-ui/registering-resources) in lovelace dashboards. Hence, you do this manually, or through HACS that does exactly the same but with an automatic process and notifying you about updates.
Regards

**Comment by Niek** [comment]
Thanks @elchininet - I am aware that it's a super easy (manual) install. I was wondering if it's possible to "abuse" the supervisor or REST API to inject the JS file programatically, so the install&update process is even easier. Glancing over the API docs, it's not so easy though. Thanks again!

**Comment by elchininet** [comment]
Yes @Niek,
Each approach serves to different purposes, If would like to make a container to expose an API, interact with HA supervisor, serve an UI end-point to expose it through ingress, etc, an add-on is the way to go. But for injecting a `JavaScript` file into the lovelace views this is the approach that HA has implemented.
Welcome!
