### ISSUE TITLE
[BUG] hide_dialog_attributes not working for light entity

### ISSUE THREAD

**Issue by dhoeben** [NemesisRE/kiosk-mode#117]
**Describe the bug**
with hide_dialog_attributes set to true, it does still display the attribute menu in the  light entity more info pop-up.

**To Reproduce**
1. Go to *a light*
2. Click on more info
3. Scroll down to attribute
4. See attribute menu still there

**Expected behavior**
attributes menu to be hidden

**Versions:**
 - Home Assistant: 2023.9.3
 - Kiosk-Mode v4.0.0

**Additional context**
Awesome kiosk mode, love the new feature to hide items in the more-info dialogs!

**Comment by elchininet** [comment]
Hi @dhoeben,
I‘ll check it out and I‘ll let you know.
Regards

**Comment by elchininet** [comment]
Hi @dhoeben,
When [this pull request](https://github.com/NemesisRE/kiosk-mode/pull/118) gets merged and a new version is released, you issue will be solved.
Just remember that `kiosk-mode` only works on `lovelace` dashboards, so if you open the more-info dialog in another dashboard (like the devices dashboard) this will not work.
Regards

**Comment by dhoeben** [comment]
Thank you for the advice quick fix! For your information, indeed I used it in a Lovelace dashboard with 
/ adde
/d.

**Comment by elchininet** [comment]
Hi @dhoeben,
This issue will be closed automatically when the pull request gets merged.
Regards
