### ISSUE TITLE
[BUG] HA 2023.10.x : hide_dialog_media_actions hide the on/off switch toggle and light slider

### ISSUE THREAD

**Issue by BoneheadFraggle** [NemesisRE/kiosk-mode#120]
**Describe the bug**
 - After updating to HA 2023.10.x (.3 in my case), the setting hide_dialog_media_actions hide the `switch` on/off toggle and the `light` slider
 
```hide_dialog_media_actions: false```
![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/b5d1b9c4-8668-4270-88d2-7f0937e8e8fb)

![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/0410c834-f26e-4f2c-92fe-34f76262ce4a)

```hide_dialog_media_actions: true```
![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/1d778798-f4ae-4470-b5eb-e4ef34885f78)

![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/32a9da22-b6c2-4571-9691-2cee51a3de09)

**To Reproduce**
1. use ```hide_dialog_media_actions: false```
2. Click on a switch to open `more_info`
3. See expected behavior.
4. Change to ```hide_dialog_media_actions: true```
5. Click on a switch to open `more_info`
6. See unexpected behavior.

**Versions:**
 - Home Assistant: [e.g. 2023.10.3]
 - Kiosk-Mode [e.g. v4.1.0]

**Comment by elchininet** [comment]
Hi @BoneheadFraggle,
I‘ll take a look at it, most probably it was introduced with [this change](https://github.com/NemesisRE/kiosk-mode/issues/117).
Regards

**Comment by elchininet** [comment]
Hi @BoneheadFraggle,
Let me know if [this version](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) solves the issue.
Regards

**Comment by BoneheadFraggle** [comment]
> Hi @BoneheadFraggle, Let me know if [this version](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) solves the issue. Regards

@elchininet 
Yep! Everything I have been able to test works great again. with that version.  
Great work. Thanks!

**Comment by elchininet** [comment]
Perfect @BoneheadFraggle,
When [this pull request](https://github.com/NemesisRE/kiosk-mode/pull/121) gets merged and a new version is released, you can install the plugin through HACS again.
Regards
