### ISSUE TITLE
hide iframe menu

### ISSUE THREAD

**Issue by moshiko2312** [NemesisRE/kiosk-mode#123]
Hi, I'm trying to work with iframe from one home assistant to another home assistant, it works and connects well, but when the screen shows iframe you still see the top menu and the sidebar screen.
Is it possible to make an update so that the restrictions I make to users can also apply to this?
Thank you in advance and a huge thank you for all your wonderful work 🙏🏻
I'm posting screenshots, hope I've explained myself well
this pic is user no menu and bar
![IMG_0018](https://github.com/NemesisRE/kiosk-mode/assets/48163773/80710d10-cb49-47a5-8d0e-113dfc0b8971)

this is after im using  iframe

![IMG_0019](https://github.com/NemesisRE/kiosk-mode/assets/48163773/828fea07-877b-4e2f-bdd4-a6d4a60fec19)
![IMG_0020](https://github.com/NemesisRE/kiosk-mode/assets/48163773/f65799b7-a66c-4007-85fa-80e5fc0f0fc0)

🙏🏻

**Comment by elchininet** [comment]
Hi @moshiko2312,

If I understood well you want to modify a Home Assistant instance that is being shown inside an iframe from the parent instance.

If that is the case, it is not possible to manipulate anything inside an iframe coming from another domain, [it is a very basic security restriction](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#scripting). You would need to make those changes directly in the Home Assistant instance that you are trying to show inside the iframe.

Regards

**Comment by moshiko2312** [comment]
Hi thanks
I have 2 kiosk mode 2 of home assistant
So I’m not understanding what actually I need to do
Can you show me how?

בתאריך יום ד׳, 18 באוק׳ 2023 ב-23:36 מאת Iván Pereira <
***@***.***>:

**Comment by elchininet** [comment]
Hi @moshiko2312,

What I mean is that if you have two Home Assistant instances any change in one will not affect the other, and this holds truer if both instances are in [different origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). 

In summary, if you want to change something in the instance that is shown inside the iframe you need to go there to its configuration and do it, but nothing that you do in that instance will affect the other and vice versa.

Regards

**Comment by elchininet** [comment]
Hi @moshiko2312,
Closing this request because it is impossible to develop something from `kiosk-mode` to achieve what you are seraching for.
But you can open [a discussion](https://github.com/NemesisRE/kiosk-mode/discussions) and I can give you some ideas to communicate two home assistant instances through automations.
Regards

**Comment by moshiko2312** [comment]
Ok thanks

בתאריך שבת, 21 באוק׳ 2023 ב-13:53 מאת Iván Pereira ***@***.***
