### ISSUE TITLE
How to turn off kiosk mode?

### ISSUE THREAD

**Issue by Bagunda** [NemesisRE/kiosk-mode#124]
I turned on kiosk mode.
Now how can I go into editing Lovelace?
There is no menu (three dots).

![image](https://github.com/NemesisRE/kiosk-mode/assets/16766521/0fa672e0-b9d8-48c9-b73d-f17d4114bb10)

**Comment by NemesisRE** [comment]
https://github.com/NemesisRE/kiosk-mode#important-info
