### ISSUE TITLE
[BUG] JavaScript Error on page load "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by tecbird** [NemesisRE/kiosk-mode#146]
**Describe the bug**
![image](https://github.com/NemesisRE/kiosk-mode/assets/16688055/19175281-47aa-4d8c-933c-dd37ac79370a)
![image](https://github.com/NemesisRE/kiosk-mode/assets/16688055/cadcf269-fdbb-4f6d-b8ca-a8f2af0d92eb)

**To Reproduce**
1. Load any lovance dashboard

**Expected behavior**
Nothing happened, kiosk mode not working.
I tried also any GET query parameter, but nothin worked.

**Screenshots**
See above

**Versions:**
 - HA Core: 2023.11.3
 - HA Frontend: 20231030.2
 - Kiosk Mode: 4.6.0

**Comment by elchininet** [comment]
Hi @tecbird,
Please, paste your configuration related to `entity_settings`, you should have an error there.
Regards

**Comment by elchininet** [comment]
Hi @tecbird,
Could you share your config?
Without seeing your config it would be impossible to help you out.
Regards

**Comment by elchininet** [comment]
Hi @tecbird,
It seems that either you solved your issue or you are not interested in solving it anymore.
Either way, closing this issue.
Regards
