### ISSUE TITLE
[BUG] chaining of query strings seems to be broken

### ISSUE THREAD

**Issue by stonith** [NemesisRE/kiosk-mode#148]
**Describe the bug**

Using a single query string works like `?hide_sidebar`, however if I use `?hide_sidebar?hide_search` neither parameters work and the default view is loaded.

**To Reproduce**
1. Go to 'HA UI with `?hide_sidebar?hide_search'

**Expected behavior**
Sidebar and Search button are hidden

**Versions:**
 - Home Assistant: 2023.12.1
 - Kiosk-Mode [v4.6.0]

**Additional context**
I've worked around by using the dashboard config yaml instead which works.

**Comment by elchininet** [comment]
Hi @stonith,
Please, check [this](https://github.com/NemesisRE/kiosk-mode/issues/145).
Regards
