### ISSUE TITLE
[BUG] Attributes not hidden in HA 202312.x

### ISSUE THREAD

**Issue by BoneheadFraggle** [NemesisRE/kiosk-mode#149]
**Describe the bug**
 In HA 2023.12.x, the setting `hide_dialog_attributes: true´ is no longer effective.

**To Reproduce**
1. Configure `hide_dialog_attributes: true`
2. Click on a sensor with an attribute
3. The Attribute section is still visible

**Expected behavior**
In HA 2023.11.x it hid the attribute section.

**Screenshots**

HA 202311.2:

![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/5d6d11d1-3a9c-498a-b624-13bad2f39b2c)

HA 202312.1:

![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/1690e30d-d13c-472d-b457-159d10d55bdd)

**Versions:**
 - Home Assistant: 202311 / 12
 - Kiosk-Mode 4.6.0

**Additional context**
Just want to say I really appreciate your effort!

**Comment by elchininet** [comment]
Hi @BoneheadFraggle,
Indeed, they changed the path of the attributes.
To avoid cluttering the more-info dialogs logic with multiple conditions, I‘ll remove the support that we are giving at the moment to `<= 2023.8.x` installations, and after that I‘ll add a condition to support `<= 2023.11.x` and `> 2023.11.x` installations, so users that have not migrated yet will get the same experience.
Regards

**Comment by elchininet** [comment]
Hi @BoneheadFraggle,
The pull request is ready, there are more options broken with `2023.12.x` but it was relatively easy to fix because right now we count with a new method to select DOM elements.
Regards
