### ISSUE TITLE
Dependabot pull request always fail in the E2E tests

### ISSUE THREAD

**Issue by elchininet** [NemesisRE/kiosk-mode#167]
**Describe the bug**

This [PR opened by Dependabot](https://github.com/NemesisRE/kiosk-mode/pull/163) failed in the E2E several times, [the same changes opened by me](https://github.com/NemesisRE/kiosk-mode/pull/165) passed without issues.

This [PR opened by Dependabot](https://github.com/NemesisRE/kiosk-mode/pull/164) failed in the E2E several times, [the same changes opened by me](https://github.com/NemesisRE/kiosk-mode/pull/166) passed without issues.

It seems a clear pattern that the runners that pick Dependabot PRs fail for some reason, we need to investigate why this happens, if not Dependabot lose any sense.

**Comment by elchininet** [comment]
[This is relevant](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions)

>Secrets are populated from Dependabot secrets. GitHub Actions secrets are not available.

We use a token to call the Home Assistant API and this token cannot be retrieved by the actions triggered by Dependabot. That is the reason why the test that fails are those that require to call the API to change the state of entities.

**Comment by elchininet** [comment]
[Relevant](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#adding-a-repository-secret-for-dependabot)

**Comment by elchininet** [comment]
@NemesisRE, could you perform the steps in the last link above? It is just to paste the same secret under Dependabot secrets with the same name and the same content. And hope that this solves the issue.

**Comment by NemesisRE** [comment]
Done

**Comment by elchininet** [comment]
Let‘s wait for the next dependabot update to see if it finishes without issues. 👍

**Comment by elchininet** [comment]
@NemesisRE,
[It is working for the E2E tests](https://github.com/NemesisRE/kiosk-mode/pull/169). I am seeing that the CodeQL task is not finding some configuration, we need to investigate why (maybe it is related to the same).
