### ISSUE TITLE
[FR] Request feature  to hide back button 

### ISSUE THREAD

**Issue by dhoeben** [NemesisRE/kiosk-mode#176]
Hi,

Request a mode to hide the back button when `subview: true` is set in view.
I made my own menu and I don't want to hide the menu bar, but I do want to hide the back button.

Can you implement this feature please?

Thank you.

**Comment by elchininet** [comment]
Hi @dhoeben,

That falls out of the scope of this plugin which is not intended to hide random elements but those elements that are critical to avoid unauthorized users to interact with them in a kiosk-device.

But I‘ll see if it is posible to achieve what you are searching with alternative solutions. If I find a wauy to do it I‘ll add it to [kiosk-mode complements](https://github.com/NemesisRE/kiosk-mode/blob/master/KIOSK-MODE-COMPLEMENTS.md).

**Comment by dhoeben** [comment]
Hi @elchininet ,

thanks for the quick reply. I actually want to hide it for unauthorized users. That’s why I created my own menu, which navigates between two subviews. Unfortunately even if you open the subview via link, the back button still brings them back to the main part (not allowed).

thansk anyhow! I will keep an eye out for the complements!

cheers

**Comment by elchininet** [comment]
Hi @dhoeben,

That is something specific of your set up, if you don‘t want users to return to a view that they should not access you should create the subview from a view that they have access in the first place. Kiosk mode is not inetended to solve specific use cases, for specific use cases you should use generic and flexible approaches.

[I have added a solution for your use case to the kiosk mode complements](https://github.com/NemesisRE/kiosk-mode/pull/177), you achieve what you are searrching in that way.

Regards
