### ISSUE TITLE
3-dots disappear when toggling a Kiosk mode selector in narrow view

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#18]
referenced in https://github.com/NemesisRE/kiosk-mode/issues/16#issuecomment-1473618359_
            
please see:

![Mar-17-2023 11-50-57](https://user-images.githubusercontent.com/33354141/225885129-daa8763c-6e43-4ec0-a563-bfda694aaa20.gif)

need to widen the view again and toggle once more to get the 3-dots back

it does not matter which of the toggles is toggled, any of the above shown in the video has the same result,

btw, as you can see above, this specific toggle does not bring back the hamburger menu icon to the left either....

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

We need to narrow down the issue again, I cannot reproduce it.

Some things that could influence:

* Which device are you using?
* Browser and version?
* Home Assistant version?

It would be helpful if you can debug it and check which styles are applied to the overflow menu and what is the structure of the HTML that you get.

![Screencast](https://user-images.githubusercontent.com/3728220/226060882-47494203-be57-4efb-9076-55138ba4009b.gif)

**Comment by Mariusthvdb** [comment]
well, I did see it on all of my browsers, I'm on ha 2023.3.5 Mac computer

but, it must have to do with

```
mobile_settings:
  hide_menubutton: true
  hide_overflow: true
#   ignore_entity_settings: true
```

which I have set in the main kiosk-mode configuration.
I commented that now and reloaded, but n change. Guess we can not change that without a restart?

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

I don‘t see any method to re-run all the logic to apply the styles on window resize events, only on first load and when the panels are changed, so it makes sense that it doesn‘t do anything during this event.

As I understand the issue in the description was provoked by another configuration to hide those elements on mobile devices right? If that is the case, let‘s close this issue and open a new one describing that the styles are not refreshing on windows resize events.

On the other hand, resizing the window from desktop to mobile and vice versa, is not something that the majority of user do, if you can describe in the issue what is your use case and why do you need to change the window‘s size using the kiosk-mode plugin, it will help to understand better why it is needed.

Regards.

**Comment by Mariusthvdb** [comment]
sorry for the delay....

though I dont consider this an edge case, and would think resizing windows is core functionality, it might be core HA functionality, and not Kiosk mode functionality.

I'll close here, because the main topic indeed is solved, as your correctly state. thanks for the support!
