### ISSUE TITLE
hide_sidebar and landscape not working

### ISSUE THREAD

**Issue by joaopedros2** [NemesisRE/kiosk-mode#181]
I checked this issue today while testing on a tablet in landscape mode, and the side menu doesn't disappear, it only works in portrait mode. I also tested it on my smartphone, and the problem persists.

**Comment by elchininet** [comment]
Hi @joaopedros2,

Please, follow the template to open an issue and give all the information that is required to debug an issue further.

Regards

**Comment by elchininet** [comment]
Hi @joaopedros2,
Please, update your issue providing all the details required in the template so we can try to debug it further.
Regards

**Comment by elchininet** [comment]
Hi @joaopedros2,
It seems that you already solved your issue or it doesn‘t interest you anymore.
In any case, closing this issue.
Regards
