### ISSUE TITLE
Panel_iframe and dashboard 

### ISSUE THREAD

**Issue by moshiko2312** [NemesisRE/kiosk-mode#187]
hi can you please   add options to hide  panel_iframe in sidebar bar and some  dashboard

dashboard Editor phone 
<img width="159" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/48163773/dfec02b2-5649-4448-9aff-e89a0ad22da1">

my configuration  yaml

panel_iframe:
  configurator:
    title: File Editor
    icon: mdi:wrench
    url: 'http://10.0.0.253:3218'  
<img width="149" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/48163773/2e13a5e7-fecb-402e-a3a7-5e7af1d7b006">

![de](https://github.com/NemesisRE/kiosk-mode/assets/48163773/3a49c326-41d5-49c8-9a5d-4ad3dab98ddb)

**Comment by elchininet** [comment]
Hi @moshiko2312,
Please, refer to [this issue](https://github.com/NemesisRE/kiosk-mode/issues/168) and the alternative given there. Kiosk-mode is intended to hide fixed elements that cannot be hidden by other means, elements that are dynamic or managed by the users are outside of the scope of this plugin.
Regards

**Comment by moshiko2312** [comment]
Thanks

בתאריך יום ו׳, 19 בינו׳ 2024 ב-19:54 מאת Iván Pereira <
***@***.***>:
