### ISSUE TITLE
[ERROR] TypeError: Cannot read properties of undefined (reading 'hass')

### ISSUE THREAD

**Issue by RiderCrazy** [NemesisRE/kiosk-mode#189]
Hello,

I've just saw this error in console while inspecting.
Everything is up to date.
Errors counting since last reboot, less than 5 minutes ago.

![image](https://github.com/NemesisRE/kiosk-mode/assets/78437975/1ccdbdca-2fe4-499e-826b-f7719ba3c525)

**Versions:**
 - Home Assistant: 2024.1.4
 - Kiosk-Mode: 5.2.0

**Comment by elchininet** [comment]
Hi @RiderCrazy,
Following the stack trace, it originated from an entity change. Could you share your config and what are those entities that you are watching for changes?
Regards

**Comment by RiderCrazy** [comment]
Hi @elchininet,
I have launch the console again after your message, no more errors ¯\_(ツ)_/¯

**Comment by elchininet** [comment]
Hi @RiderCrazy,
That‘s wierd, just open an issue if you detect that is something that happens consistently.
Regards

**Comment by Drealine** [comment]
Hi @RiderCrazy i've the same problem. But I don't known what entity create the problem.

**Comment by Drealine** [comment]
`  domain: system_log
  service: write
  service_data:
    logger: frontend.js.latest.202401040
    message: >-
      Unhandled promise rejection from Brave 121.0.0.0 on Mac OS 10.15.7

      TypeError: Cannot read properties of undefined (reading 'hass')

      t.<anonymous> (/hacsfiles/kiosk-mode/kiosk-mode.js:1:43922)

      /hacsfiles/kiosk-mode/kiosk-mode.js:1:1499

      Object.next (/hacsfiles/kiosk-mode/kiosk-mode.js:1:1604)

      /hacsfiles/kiosk-mode/kiosk-mode.js:1:520

      e (/hacsfiles/kiosk-mode/kiosk-mode.js:1:265)

      t.entityWatchCallback (/hacsfiles/kiosk-mode/kiosk-mode.js:1:43790)

      Object.callback (/hacsfiles/kiosk-mode/kiosk-mode.js:1:43661)

      callback
      (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
    level: debug`

**Comment by Drealine** [comment]
100errors each minute.
