### ISSUE TITLE
[FR] Allow to control kiosk content using automations

### ISSUE THREAD

**Issue by wasyl00** [NemesisRE/kiosk-mode#203]
**Is your feature request related to a problem? Please describe.**
No, just interesting suggestion

**Describe the solution you'd like**
I'm in the process of building home dashboard but want to include face based recognition with use of cam/frigate/double take. It would very nice to be able to display specific dashboard based on person standing in front of it. It would also be nice to display alternative content (like guest dashboard) or hide it completely when unauthorised is being recognised by the system. 

Is it even possible for kiosk to execute such actions provided it gets triggers from HA?

Cheers

**Comment by NemesisRE** [comment]
No it is not possible. Kiosk mode is a tool to lock down the UI to allow only certain actions or even only read-only access.

There could be other ways to do what you want and kiosk mode could help by its intended use case.

**Comment by wasyl00** [comment]
Thanks for the info. Great project btw
