### ISSUE TITLE
[BUG] Does hide_edit_dashboard in URL work?

### ISSUE THREAD

**Issue by sbussinger** [NemesisRE/kiosk-mode#206]
When I try to access my dashboard with "https://homeassistant:8123/lovelace-dashboard/dashboard?hide_edit_dashboard", the edit icon still shows up and I don't think it should. 

![image](https://github.com/NemesisRE/kiosk-mode/assets/706838/e85976a3-0411-4295-b961-bb2cacd47d4b)

**Versions:**
 - Home Assistant: [2024.2.5]
 - Kiosk-Mode [v5.3.0]

**Comment by NemesisRE** [comment]
It would help if you fill out the bug template so that we know which versions you are using.

**Comment by sbussinger** [comment]
Whoops! Sorry about that! I forgot to go back and put the actual version numbers in the comment. I've edited the original comment to include them, but just in case, they're the current versions of both:

**Versions:**
 - Home Assistant: [2024.2.5]
 - Kiosk-Mode [v5.3.0]

**Comment by sbussinger** [comment]
I should also mention that other URL parameters like "hide_search" work fine.

And thanks for a very handy tool!

**Comment by elchininet** [comment]
Hi @sbussinger,

I am seeing that some things have changed in the layout. Previously, in that position was located the overflow menu (that could be hidden using the `hide_overflow` option). In this image the number `8`:

![Overflow menu](https://raw.githubusercontent.com/NemesisRE/kiosk-mode/master/images/lovelace-dashboard.png)

When one opened that menu, this was the result:

![Overflow Menu Open](https://raw.githubusercontent.com/NemesisRE/kiosk-mode/master/images/overflow-menu.png)

The item `12` is what `hide_edit_dashbiard` tries to hide at the moment. This should be refactored to deprecate options that are not needed anymore and to support the new cases, but it requires to check what happens in storage and yaml mode to make it work for both. I‘ll take a look when I have some time and I need to add those cases to the tests to be able to spot it next time that it happens.

**Comment by NemesisRE** [comment]
great thank you @elchininet

**Comment by elchininet** [comment]
I am seeing what happened, that change was done only in `storage` mode, in `yaml` mode everything continues as it was. The tests are in `yaml` mode, so it will be hard to add that check to the tests but at least I‘ll try to fix it for `storage` mode.

![image](https://github.com/NemesisRE/kiosk-mode/assets/3728220/e286a573-35a5-4a85-b51f-c64dac05e818)

**Comment by elchininet** [comment]
@sbussinger,

As the change was only in `storage` mode and only in desktop (in mobile things remain as they were), the change was pretty straighforward. It will work for the new version and it will keep working with previous versions.

When [this pull request](https://github.com/NemesisRE/kiosk-mode/pull/207) gets merged and a new version is released, your issue will be solved.

Regards

**Comment by sbussinger** [comment]
Thank you both for fixing this! It's working great now.

**Comment by elchininet** [comment]
>Thank you both for fixing this! It's working great now.

Glad to hear that 🙂
