### ISSUE TITLE
Kiosk mode in an android webview

### ISSUE THREAD

**Issue by mph070770** [NemesisRE/kiosk-mode#209]
![image](https://github.com/NemesisRE/kiosk-mode/assets/508539/3951ba85-df09-48cb-bc21-52ff9ed75516)

Kiosk mode 5.4.0

Hi.
I'm developing an overlay app that will show HA information in a floating webview on top of a TV running android TV.  So, my app is effectively just an android app with the ability to show a webview.

I have kiosk mode working in chome on my PC (so know it's working):

![image](https://github.com/NemesisRE/kiosk-mode/assets/508539/37e302af-794c-4d90-a900-d839a49ba43a)

However, when I open the same URL in the webview on my android simulator (or android device), the webview is shown with the blue top banner still shown:

![image](https://github.com/NemesisRE/kiosk-mode/assets/508539/3940259d-9e1a-4dcb-a318-c6d16e6f1d78)

I don't know what techniques you use to get rid of the banners but any ideas why it might not work in the webview?

Note, to use the webview without needing to sign into HA, I use external authentication which adds an additonal query string to the URL:

http://192.168.1.73:8123/dashboard-gardencamonly/0?external_auth=1?kiosk

however, I have also tried:

http://192.168.1.73:8123/dashboard-gardencamonly/0?external_auth=1

with:
kiosk_mode:
  hide_header: true
views:
added to the lovelace dashboard.

Any help would be great, thank you!

**Comment by NemesisRE** [comment]
Chaining parameters is not standardized but the de facto standard is to use ampersand (&)

Anyway we have a similar situation were the blue top stays with ios devices but it seams in your case it's not only the blue top but the whole menu.

I guess we would need a check if kiosk mode is loaded in this situation maybe it is blocked by something.

**Comment by elchininet** [comment]
>http://192.168.1.73:8123/dashboard-gardencamonly/0?external_auth=1?kiosk

This is a malformed URL:

<img width="682" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/3728220/082b33ec-8d8b-4de9-8a83-7535d1e34f11">

This is a correct URL:

<img width="683" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/3728220/bd9d4c4a-d11d-46aa-8925-a0bbb3e132a2">

Try to debug the logs and search for WebView errors. Make sure [to enable JavaScript](https://developer.android.com/reference/android/webkit/WebSettings#setJavaScriptEnabled(boolean)) (most probably you have it enabled) and also `kiosk-mode` uses `localStorage, make sure you enable [the DOM storage API](https://developer.android.com/reference/android/webkit/WebSettings#setDomStorageEnabled(boolean)).

**Comment by mph070770** [comment]
Thanks for your quick support.  Thanks for pointing out my misunderstanding with the chaining of parameters.  I'll get that fixed.

I enabled DOM storage in my webview and can confirm that when I have kiosk mode enabled in the dashboad yaml, the blue banner is removed.  It is briefly shown as the page is drawn and then dissapears.  It would be good to fix that too but that's a problem for another day...

Thanks again - great feedback!

**Comment by elchininet** [comment]
Good to know @mph070770!

Unfortunately, a delay will occur on page load because `kiosk-mode` needs to wait for the elements being rendered and accessible through the DOM to be able to manipulate their styles.

Regards 👍🏼
