### ISSUE TITLE
[FR] secure mqtt

### ISSUE THREAD

**Issue by lerra** [NemesisRE/kiosk-mode#214]
To start with, I just want to say that really like the project, the only thing I am missing is secure mqtt, preferably with client certificate.

Any plans for secure mqtt?

**Comment by NemesisRE** [comment]
How is mqtt related to our ui mod?

**Comment by lerra** [comment]
Hi, i'm sorry, I thought it was the same as the android app that was announced in the home [assistant facebook group and the reference from the author](https://www.facebook.com/groups/HomeAssistant/posts/3702312060040137/?comment_id=3702350360036307&reply_comment_id=3702365670034776) on the repo question was this repo

**Comment by elchininet** [comment]
Hi @lerra,

That is an Android application, it is not related at all to this `JavaScript` plugin that is intended to hide or block DOM elements from the Home Assistant interface.

I think that the author is using this plugin to hide the Home Assistant elements and the Android application to remove the native header and controls and set the application to full screen. I have a similar set up, but using [Fully-Kiosk](https://www.fully-kiosk.com) instead. `Fully Kiosk` don‘t use MQTT but it is possible to control the remote device using [the Fully Kiosk Browser integration](https://www.home-assistant.io/integrations/fully_kiosk/).

Closing this issue.

Regards
