### ISSUE TITLE
Hide Effect button on Light More Info Card

### ISSUE THREAD

**Issue by direx1** [NemesisRE/kiosk-mode#218]
Would it be possible to add an option to hide the effect button on a light's more-info card like there is for the media card which uses:
hide_dialog_media_actions: true

Perhaps something like:
hide_dialog_light_effect_actions: true

Thanks.

**Comment by elchininet** [comment]
Hi @direx1,
I‘ll take a look at it and I‘ll let you know if it is something achievable.
Regards

**Comment by elchininet** [comment]
Hi @direx1,
[This pull request](https://github.com/NemesisRE/kiosk-mode/pull/221) contains the changes to implement the new option that you requested. It needs to wait for [this pull request](https://github.com/NemesisRE/kiosk-mode/pull/220) to be merged first. When everything is merged an a new version of the plugin is released, you can use the new option to hide the light effects.
Regards

**Comment by elchininet** [comment]
Hi @direx1,
A new version has been released, you can test the feature and let us know.
Regards

**Comment by direx1** [comment]
> Hi @direx1, A new version has been released, you can test the feature and let us know. Regards

Working great. Thanks.

**Comment by elchininet** [comment]
Super, thanks for confirming 👍
