### ISSUE TITLE
Feature request: Control light / dark mode

### ISSUE THREAD

**Issue by jessemcdowell** [NemesisRE/kiosk-mode#22]
Is it possible to control the user's light/dark mode setting from this module? It would be great to force my wall-mounted dashboard panel into dark mode.

**Comment by elchininet** [comment]
Hi @jessemcdowell,

This plugin is intended to hide elements from the DOM, not to change Home Assistant settings. Why don‘t you just turn on manually the dark mode in the device? (I enabled dark-mode in my wall-mounted tablet before activating `kiosk-mode` on it)

Regards

**Comment by jessemcdowell** [comment]
Fair enough. Sometimes I'm the wrong kind of lazy. I'm pretty new to Home Assistant so I wasn't sure how possible it would be.

I'll withdraw my suggestion.
