### ISSUE TITLE
Possible to hide mouse cursor?

### ISSUE THREAD

**Issue by reloadxero** [NemesisRE/kiosk-mode#24]
I'm displaying home assistant dashboards on 2 seperate samsung tv display's default internet browser on kiosk mode by adding "?kiosk" to the end of the dashboard url. When the tvs turn on, per tv setting it automatically opens the last opened app and opens the default homepage which points to my homeassistant instance and automatically logins via trusted_networks and trusted_users. Everything is working fine yet one thing that annoys me is the big fat tv browser cursor that sits in the middle of the screen, which i have to manually move to a corner so i can hide it.

Would it be possible to add a switch to hide the cursor in css or js level coding (sorry i don't know if this correct terminology, i'm noob)?

**Comment by elchininet** [comment]
Hi @reloadxero,
This [pull request](https://github.com/NemesisRE/kiosk-mode/pull/25) implements a block mouse option, but it will not be merged until it is reviewed by the repo owner and a new version is released.
As I mentioned, it is not certain that this will work specifically on your TV but it doesn‘t hurt if you try it.
Regards
