### ISSUE TITLE
[BUG] hide_dialog_attributes not working on lock entity

### ISSUE THREAD

**Issue by BjornWill** [NemesisRE/kiosk-mode#251]
**Describe the bug**
When setting the hide_dialog_attributes to 'true' this seems to work for every entity except for locks
 - Console log errors (F12)

**To Reproduce**
1. add the hide_dialog_attributes value 'true' to the dashboard
2. Open any lock entity

**Expected behavior**
Using the value hide_dialog_attributes should hide the attributes dropdown from every more-info pane in the dashboard.

**Screenshots**
![afbeelding](https://github.com/NemesisRE/kiosk-mode/assets/76884987/0d29dcc6-3322-4018-8558-f69951a4dcd9)

**Versions:**
 - Home Assistant: v2024.7.1
 - Kiosk-Mode v6.0.1

**Comment by elchininet** [comment]
Hi @BjornWill,

For the dialogs elements, we basically hide them taking the reports and feedback of users, as there are so many entities and dialogs types it is very hard to make it work everywhere at once.

I'll try to debug this with that kind of entity and add the necessary code to support it. 

Regards

**Comment by elchininet** [comment]
Hi @BjornWill,
Once [this pull request](https://github.com/NemesisRE/kiosk-mode/pull/253) is merged and a new version is released, your issue should be solved.
Regards

**Comment by elchininet** [comment]
Hi @BjornWill,
[A new version](https://github.com/NemesisRE/kiosk-mode/releases/tag/v6.1.0) has been released. Please, install it and check that your issue is solved.
Regards
