### ISSUE TITLE
[FR] Hide '>' button of history graph

### ISSUE THREAD

**Issue by FRvanderVeen** [NemesisRE/kiosk-mode#255]
**Is your feature request related to a problem? Please describe.**
I do have a history graph (card `type: history-graph`) on my dashboard. In the top right corner it has the `>` button, which links to `/history`.

**Describe the solution you'd like**
I would like to be able to hide that button.

**Describe alternatives you've considered**
Using something like `card-mod`, but that will hide it for every user and not some users.

**Additional context**
![image](https://github.com/user-attachments/assets/95e9cbfb-92e4-4dbb-8ecf-71720ba43843)

**Comment by elchininet** [comment]
Hi @FRvanderVeen,
Please, refer to [this discussion](https://github.com/NemesisRE/kiosk-mode/discussions/128). `Kiosk-mode` is not intended to change cards behavior.
Regards
