### ISSUE TITLE
[FR] Automatically reload when dashboard is updated?

### ISSUE THREAD

**Issue by shadow7412** [NemesisRE/kiosk-mode#262]
**Is your feature request related to a problem? Please describe.**
Although there is a means to hide the refresh popup, there doesn't seem to be a way to automatically action it.

**Describe the solution you'd like**
I'd like the dashboard to automatically reload when the dashboard changes. That would means that kiosks, especially ones with all interaction disabled, can always be running the latest version. It'd also be a nice way to quickly make changes on another device (such as a phone) and have the kiosk quickly reflect those changes.

Naturally, I'd expect this to be a behaviour one would opt into as there would likely be setups for which this would be a detriment.

**Describe alternatives you've considered**
I haven't really considered alternatives. Building this in feels like a pretty logical place for it to be, in my mind.

**Additional context**
N/A

**Comment by NemesisRE** [comment]
I think this is valid and makes sense but it could/should be an independent plugin.
As an individuell plugin it would be opt in by nature and people that do not use kiosk-mode could also benefit from it ([those](https://community.home-assistant.io/t/solved-how-can-i-get-my-dashboard-to-refresh-automatically-instead-of-showing-the-refresh-prompt/357842/78))

**Comment by shadow7412** [comment]
I can definitely understand that argument.

**Comment by elchininet** [comment]
Hi @shadow7412,
I agree with @NemesisRE, that is a global funtionality not tightly related to `kiosk-mode`. If `fully-kiosk` is used, that could be achieved [with an automation](https://community.home-assistant.io/t/solved-how-can-i-get-my-dashboard-to-refresh-automatically-instead-of-showing-the-refresh-prompt/357842/22). Try it out, it seems pretty simply to achieve.
Closing this issue.
Regards

**Comment by shadow7412** [comment]
I'm not using fully-kiosk - it's just a browser running on a windows tablet.

I feel like the convenience factor of being able to easily configure this with the granularity kiosk-mode provides makes this a feature worth a little more consideration... but ultimately it's your call. I appreciate the links you've given me.

**Comment by elchininet** [comment]
Hi @shadow7412,

Then your best option is to create a JavaScript plugin to do that automatically for you.

It is normal and understandable that someone find convenient to have some specific functionalities that satisfy their use cases in a granular plugin as `kiosk-mode`, but it is the work of the maintainers to keep the plugin focused with its main goal and avoid it becoming a `do-it-all` that would make it unmaintainable in the future.

Try to use some of the scripts in the thread and if you need help don‘t hesitate to ask it here, I can help you out if something fails on your side or if you get stuck.

> Note: I am seeing [this plugin](https://github.com/ben8p/lovelace-auto-reload-card) that refreshes the dashboard every x time, but I don‘t know if it is working at the moment with the latest versions of Home Assistant.

**Comment by shadow7412** [comment]
Thanks for the link - it's a pretty solid bare-bones example of how I could pull this off, if that solution doesn't work. And I totally appreciate the need to keep the plugin focused.

Hopefully I can find some time this weekend to have a solid crack at it.

**Comment by elchininet** [comment]
Let me know how it goes 👍🏼

**Comment by shadow7412** [comment]
So I did get this working. I decided to adapt one of those links above to be a tampermonkey script (I only wanted it to happen on the one computer, and this was an easy enough way to achieve that). Then I discovered browser-mod which has a bunch of functionality that is of interest - but some of that functionality relies on receiving user input after a reload...

So basically, I've come full circle on this. I don't want parts of the functionality to die because it auto-refreshed, so seeing as it basically requires someone anyway, we're back to begrudging acceptance of the need to click the screen when the dashboard is changed.

Thanks again for the links you provided - even though I ended up tearing it all out anyway :wink:

**Comment by rhysperry111** [comment]
If I were to submit this as a PR would it be accepted?

While I understand some of the arguments for having it be separate, it also feels like something that will be extremely useful to have and commonly needed for kiosk devices without having to pull in more add-ons than needed.

**Comment by elchininet** [comment]
>If I were to submit this as a PR would it be accepted?
>
>While I understand some of the arguments for having it be separate, it also feels like something that will be extremely useful to have and commonly needed for kiosk devices without having to pull in more add-ons than needed.

Hi @rhysperry111,

If it depends on myself no. Leting @NemesisRE to decide.

There are infinite things that are very useful for kiosk devices depending on the configuration or set up of each user, but it is not feasible that all those features are concentrated in a single plugin for the reasons that were already given. Including every feature request that comes and not saying no to things that cross the border of the plugin functionalities will eventually led to bugs, performance issues, incompatibilities with future versions, and a large number of things that are the same that made the previous `kiosk-mode` version or its sister plugin `custom-header` [to die](https://community.home-assistant.io/t/custom-header/155399/1100). And as @maykar stated in his farewell post, it is healthy to say no on time.

Let's wait for @NemesisRE, it is up to him to accept the pull request or not.

Regards

**Comment by rhysperry111** [comment]
Cool - no worries. I'll look into making one then although it'll probably take me some time to get familiar with how Home Assistant works internally.

**Comment by elchininet** [comment]
>Cool - no worries. I'll look into making one then although it'll probably take me some time to get familiar with how Home Assistant works internally.

Look at the `kiosk-mode` dependencies. I have created some `JavaScript` packages for selecting Home Assistant elements easily. I can help you out to set up a base project and you can continue from there. I think that it would be a project that could be extended with more functionalities focused in that specific scope.
