### ISSUE TITLE
[FR] Force show narrow (or wide) sidebar

### ISSUE THREAD

**Issue by denisfrench** [NemesisRE/kiosk-mode#281]
**Is your feature request related to a problem? Please describe.**
It would be helpful to have a simple way to force-show the narrow sidebar on devices with screens that may otherwise hide it completely by default (eg RPi touchscreen 800x480). There may be use cases where the wide sidebar is preferred.

**Describe the solution you'd like**
A config option (eg ```show_sidebar_narrow: true```), and associated query string (which I find more useful on my kiosk) that forces displaying the narrow sidebar.

**Describe alternatives you've considered**
I have been unable to work out how to do this using card-mod/styles directly.

At the moment I am using https://github.com/DBuit/sidebar-card to build a custom sidebar, then apply a style to cut it down to resemble the in-built narrow sidebar.

This plugin introduces needless complexity and duplicated code, as I am forced to use YAML mode with views (then hide the views), whereas my regular dashboards are all IU controlled (storage mode).

**Additional context**
If there is a way to achieve this directly using card-mod/styles, that would be fine too.

Thanks for maintaining this plugin 🙂

**Comment by elchininet** [comment]
Hi @denisfrench,

That falls out of the scope of `Kiosk-mode`.
`Kiosk-mode` is not intended to styling or giving another appeareance to UI elemements, but to hide elemenent from the screen of a kiiosk device to avoid non-authorized users to interact with them.

[Custom sidebar](https://github.com/elchininet/custom-sidebar) (which I also maintain) fits more with your request. I'll check if it is something feasible to do, this is not about styles but a core Home Assistant feature that involves several UI elements, not only the sidebar.

Regards

**Comment by elchininet** [comment]
Hi @denisfrench,
It is achievable using the same Home Assistant front-end API. Feel free to open an issue in the  [custom-sidebar](https://github.com/elchininet/custom-sidebar) repo.
Regards
