### ISSUE TITLE
[FR] Hide menubutton and/or sidebar title space

### ISSUE THREAD

**Issue by denisfrench** [NemesisRE/kiosk-mode#284]
**Is your feature request related to a problem? Please describe.**
When ```?hide_menubutton&hide_header``` are applied and the sidebar is narrow, there is a block of unusable space that I would prefer hidden (and sidebar menu items moved upwards to fill):

![image](https://github.com/user-attachments/assets/b9f5d6f8-ffbd-4bf5-9783-58c2c05c2540)

**Describe the solution you'd like**
An option to hide the space the menubutton and sidebar title occupies, which also moves the sidebar buttons upwards.

**Describe alternatives you've considered**
Possibly this could be done with card-mod, but I don't have the expertise to work that out without more research and learning.

**Additional context**
This would be a useful complement to the new ```sidebar_mode:``` setting within https://github.com/elchininet/custom-sidebar

**Comment by elchininet** [comment]
Hi @denisfrench,
I'll take a look at it. If it is not possible I'll give you a `card_mod`, but without looking at it, it seems to be achievable.
Regards

**Comment by elchininet** [comment]
Hi @denisfrench,
When [this pull request](https://github.com/NemesisRE/kiosk-mode/pull/285) gets merged and a new version of the plugin is released, your issue will be solved in the new version.
Regards

**Comment by denisfrench** [comment]
That's amazing; thank you 🙏

I hope my little sponsorship is enough to at least buy you a coffee or a beer 🍺

**Comment by NemesisRE** [comment]
It's merged but our build process seems broken

**Comment by elchininet** [comment]
>It's merged but our build process seems broken

Hey @NemesisRE, what is failing?

**Comment by elchininet** [comment]
I re-ran the job, it is that specific test with the block context menu that fails a lot. I need to fix it.

**Comment by elchininet** [comment]
@NemesisRE,
I removed the tag and the latest commit. Let me fix that test and you can try another release after that.
