### ISSUE TITLE
Hide search icon.

### ISSUE THREAD

**Issue by bedbug1226** [NemesisRE/kiosk-mode#3]
Hello,

Is there any way you can merge the hide_search: from this fork into yours?

https://github.com/natehome/kiosk-mode

It would be nice to be able to hide the entity search but still have the prospect of future support.

**Comment by methratonFR** [comment]
It would be nice. I have the same need ;)

**Comment by salsaman** [comment]
This NEEDS to be done. You can nicely lock things down with this, but just pressing on the '?' brings up a list of all entities and totally negates whatever other security this adds.

**Comment by sparment** [comment]
Agreed regarding the search icon. Adding an option to hide the search icon would be greatly appreciated!

**Comment by NemesisRE** [comment]
I will merge that.
