### ISSUE TITLE
[FR] Dark mode

### ISSUE THREAD

**Issue by Klemen1337** [NemesisRE/kiosk-mode#312]
Hi, I am using kiosk mode with fully kiosk app and cannot apply dark mode to the dashboard.
Would it be possible to add URL parameter to force browser/dashboard dark mode ?theme=dark|light ?

Cheers, K

**Comment by NemesisRE** [comment]
kiosk-mode does not have a dark mode neither does it control the themes dark mode but there is a home assistant community thread with some solutions to your problem
https://community.home-assistant.io/t/change-dark-light-mode-of-default-theme-based-on-automation/516181/19

**Comment by elchininet** [comment]
@Klemen1337,
If you need some help setting up a theme just let us know. Closing this issue.
Regards
