### ISSUE TITLE
[FR] Make the query strings work on non homepages

### ISSUE THREAD

**Issue by rzfzr** [NemesisRE/kiosk-mode#321]
I'm using a browser card with a sidepage, it would be nice to hide the topbar there too:
![Screenshot 2024-12-11 142135](https://github.com/user-attachments/assets/02b9f70f-d95c-48e8-9e82-513f87c5162a)
![Screenshot 2024-12-11 142323](https://github.com/user-attachments/assets/ab3341d4-cb6c-4980-8ec6-15863ceae6ba)

**Comment by elchininet** [comment]
Hi @rzfzr,
Your first screenshot is from `HACS`, and as the description of the plugin states:

>Hides the header and/or sidebar drawer in Home Assistant **lovelace dashboards**.

`Kiosk-mode` is intended to hide elements only for lovelace dashboards.

The second screenshot is a card, check [this discussion](https://github.com/NemesisRE/kiosk-mode/discussions/128). `Kiosk-mode` is not intended to modify cards, use [card-mod](https://github.com/thomasloven/lovelace-card-mod) for that.
