### ISSUE TITLE
[BUG] hide_dialog_attributes does not hide attribute in the map card dialog

### ISSUE THREAD

**Issue by thomasgentilhomme** [NemesisRE/kiosk-mode#325]
The hide_dialog_attributes does not work in a map dialog box.
Cache was cleared and behavior is the same with edge, chrome, safari or the HA app.
the flag works fine in other cards, cf screenshot with lock card.

<img width="1228" alt="Screenshot 2024-12-23 at 1 35 40 PM" src="https://github.com/user-attachments/assets/193a8a5c-65e6-41b5-aab0-6a42d50e268c" />
<img width="1228" alt="Screenshot 2024-12-23 at 1 38 58 PM" src="https://github.com/user-attachments/assets/9065a022-e607-46d5-b6a9-7d15f64ea85a" />

 - Home Assistant: [2024.12.5]
 - Kiosk-Mode [6.4.0]

**Comment by elchininet** [comment]
Hi @thomasgentilhomme,
I'll take a look at it.
Regards

**Comment by elchininet** [comment]
Hi @thomasgentilhomme,
When [this](https://github.com/NemesisRE/kiosk-mode/pull/326) gets merged and a new version is released with that change, your issue will be fixed.
Regards

**Comment by thomasgentilhomme** [comment]
Awesome thank you very much !
