### ISSUE TITLE
Sliver of Sidebar with 2023.4 Beta patch fix

### ISSUE THREAD

**Issue by chicknlil** [NemesisRE/kiosk-mode#33]
Opening new issue as instructed in #27.

![IMG20230405175010](https://user-images.githubusercontent.com/100124187/230221756-5c330e24-6f7a-4e60-a6e5-12f962afc693.jpg)
![IMG20230405173641](https://user-images.githubusercontent.com/100124187/230221772-769d3b23-d394-4853-9954-9d0477e3a1ff.jpg)

Two different devices, two different methods of viewing HA. First is a Google Nest Hub, using DashCast. Second is a Fire Tablet (10", 2017) using Fully-Kiosk. The "sliver" is larger on the tablets using FK. This is present on both of these tablets I have set up. I've actually got another Google Nest Hub (also using DashCast) and if there's a sliver on that one, I didn't notice it.

Happy to provide any additional info, though you may need to direct me where it is first. :)

**Comment by elchininet** [comment]
Hi @chicknlil,
I have a wall tablet, I‘ll try to reproduce it there.
I‘ll let you know if I find something.

**Comment by elchininet** [comment]
Hi @chicknlil,
I cannot reproduce it, it should not be the sidebar because this one has `display: none` if you set `hide_sidebar`. I think that this is coming from other side.

![IMG_20230406_002804](https://user-images.githubusercontent.com/3728220/230226168-75c3cc08-b23d-41b6-b571-920eaa4c51b5.jpg)

**Comment by chicknlil** [comment]
I've been using `?kiosk` as part of the address in FK.  Let me try rebooting one of the tablets and see if that makes the difference.

**Comment by chicknlil** [comment]
Okay, rebooted the closest tablet, and it's still showing that sliver (so identical to that second image I posted).

On those 4 devices, I don't want the top bar or the side bar - is there a way to accomplish this outside of using `?kiosk`? The two DashCasts have their own user accounts, I could add another account for the two tablets (they display identical info), if needed..

**Comment by elchininet** [comment]
Make a test, try to disable `kiosk-mode` completely (adding `?disable_km` to the URL) and check if you are able to see something there. Whatever is that line is not coming from the sidebar (this one is completely hidden through `display: none`).

**Comment by chicknlil** [comment]
When I do the `?disable_km` I see both the top bar and the sidebar. Definitely not desired!

The slivered side bar I've been seeing is not visable in this view, however.

**Comment by elchininet** [comment]
Yes, disabling `kiosk-mode` will show the sidebar and the header, of course. Just wanted to check if you were able to see something with the library disabled, something that you assured already (trying to figure it out what could be the reason).

**Comment by elchininet** [comment]
Let‘s wait for all the pull request that I have pending and I‘ll submit a pull request from a branch that I have in local that allows one to create a fresh docker instance of Home Assistant with `kiosk-mode` preinstalled. In this way it will be easier to isolate the issue.

**Comment by chicknlil** [comment]
Sounds good. Like I said, it's more an annoyance than a problem. I'm one of those folks that's very particular about what I'm looking at, so anything being even a little bt off makes me twitchy.

**Comment by AlexKusnezov** [comment]
hey on 2023.4 kiosk mode isn't working at all, I get this when I try to trigger it:
```
http://192.168.2.109:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128178:1:5301 TypeError: null is not an object (evaluating 'i.querySelector')
http://192.168.2.109:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128178:1:5302 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
```

**Comment by Mariusthvdb** [comment]
Parkeeren?

;-)

**Comment by elchininet** [comment]
> @elchininet Parkeeren?
> 
> ;-)

You are good spotting typos in others dashboards 😂

**Comment by chicknlil** [comment]
@elchininet, for sh*ts and giggles, I poked at the Nest Hub I have in the kitchen again...
![IMG20230406101517](https://user-images.githubusercontent.com/100124187/230411276-756878fb-9ec1-4e21-9cb8-8e6fd77297c0.jpg)
No sliver at all.

Out of curiousity, on the tablet you shared, are you using Fully-Kiosk? I wonder if there's an issue with **THAT** and the latest HA release?

**Comment by elchininet** [comment]
That‘s curious indeed. Yes, I am using Fully Kiosk, it is the latest version with the latest version of HA.

**Comment by chicknlil** [comment]
That may be it, then. I'm running 1.49.1 (according to HA), and the latest release appears to be 1.50.1.

I'll snag the closer one off the wall to do the update, and see if that does the trick, and will circle back.

**Comment by elchininet** [comment]
No, I have `1.49.1`, I use [the version that you can download from their page](https://www.fully-kiosk.com/en/#download-box) not the Google play version.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/3728220/230424158-01f20733-6d2f-4ec6-935e-5020227782eb.png">

**Comment by chicknlil** [comment]
For a Fire tablet, `1.50.1` is actually the current version.
![image](https://user-images.githubusercontent.com/100124187/230426712-831d7533-1ff0-4126-b1b8-9f7a4db84507.png)

But, I **DID** solve my issue, by doing something I'd been meaning to do for awhile.

I created a new user, "tablet" with access to the views those tablets need. I logged out of my main user and into this new user, then in the user settings, told it to hide the sidebar. This eliminated the sliver.

So closing this now, since it's not only NOT a kiosk-mode issue, but perhaps a "core"/FK issue created by the 2023.4 updates.

Thanks for your time and persistence. I know @NemesisRE has sponsorship opportunities that I'll be taking advantage of - do you have a KoFi or something I can contribute to as a token of my appreciation?

**Comment by elchininet** [comment]
Thanks for the update @chicknlil!
No worries, glad that you solved it :)

**Comment by NemesisRE** [comment]
Thank you @chicknlil that is very kind of you but I didn´t do anything, @elchininet is doing all the hard work which I am very thankful :)

**Comment by chicknlil** [comment]
> By the way, this could be the reason, In my tablet, I have a special user for it and it only has permissions for some views and it is not an admin.

It originally was using my "owner" account. The new "tablet" view only has permissions for certain views.  🤷‍♂️

And @NemesisRE, it's the least I can do for you reviving one of the resources that I depend on. Now if we can just needle @elchininet into giving me a way to donate to him too...

**Comment by elchininet** [comment]
Hi @chicknlil,
I appreciate it and it is very kind of you, but no worries, I am happy to contribute to a project that I also use and depend on.
Cheers 👍
