### ISSUE TITLE
Header always showing after 2023.4 update

### ISSUE THREAD

**Issue by jmluxem** [NemesisRE/kiosk-mode#35]
I've updated my HAOS to 2023.4 and now my device that runs Kiosk Mode is always showing the Header bar. I've tried various options to disable it - user-agnostic setting, adding ?kiosk to my URL, redownloading latest version - nothing has worked so far. Anyone else experiencing the same or have a fix for this? Thanks!

**Comment by rikardronnkvist** [comment]
Same here...

**Comment by DerEmder** [comment]
same here ... I assume the dev is already working on it. At least I hope so (looks really ugly on all of my wall panels).

**Comment by elchininet** [comment]
Please, check the open issues before opening one for the same.

https://github.com/NemesisRE/kiosk-mode/issues/27
