### ISSUE TITLE
hide_header no longer working

### ISSUE THREAD

**Issue by akhan999** [NemesisRE/kiosk-mode#36]
Hi Since Upgrade to latest version
Home Assistant 2023.4.0
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230405.0 - latest

Hide_header no longer hides header

**Comment by elchininet** [comment]
Please @akhan999, it is good to read and look around a bit in the issue before opening a new one for the same.
![image](https://user-images.githubusercontent.com/3728220/230387543-bd5ff558-f0c1-40a6-8988-14c7fe953f20.png)
