### ISSUE TITLE
Please upload the latest version of the 1.8.0 kiosk-mode.js file

### ISSUE THREAD

**Issue by gzzyyt** [NemesisRE/kiosk-mode#38]
Please upload the latest version of the 1.8.0 kiosk-mode.js file

**Comment by elchininet** [comment]
Hi @gzzyyt, the latest release was buggy, it is already removed from the releases list.

**Comment by gzzyyt** [comment]
# @elchininet When can I update and support the latest version of 2023.4

**Comment by elchininet** [comment]
Hi @gzzyyt,
The version 1.8.0 that was intended for a small feature to hide the mouse cursor was buggy and it is deleted already. There is no such version anymore. If you refer where you can find the way to make `kiosk-mode` with the latest version of Home Assistant. I have given you already the thread with the solution:

https://github.com/NemesisRE/kiosk-mode/issues/27
