### ISSUE TITLE
1.8.1 Swiping right for menu seems broken

### ISSUE THREAD

**Issue by AllegedlyUndead** [NemesisRE/kiosk-mode#42]
I can no longer seem swipe right from the left edge on the Android app to get to the menus while in Kiosk Mode in release 1.8.1.

**Comment by MaroslavG** [comment]
Same here. Also I notice that custom theme [I use iOS Theme, but I check with Metro too] don't scale on mobile. My 'default' page have only couple cards to quick glance, on mobile this cards use only half of screen, and theme is displayed only in half screen, the rest is black.  Other pages in subviews where I have much more cards that filled whole screen works great.

**Comment by elchininet** [comment]
Hi @AllegedlyUndead,.

Please, check this comment:

https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492443363

Or are you able to open the sidebar when `kiosk-mode` is disabled?

Regards

**Comment by elchininet** [comment]
Hi @MaroslavG,

I think that your issue is related to this. Please, follow it.

https://github.com/NemesisRE/kiosk-mode/issues/43

Regards

**Comment by storebatfar** [comment]
I have the same issue. It started after HA release 2023.4 and this KM release 1.8.1.
Will follow https://github.com/NemesisRE/kiosk-mode/issues/43

**Comment by elchininet** [comment]
@AllegedlyUndead,
It would be good that you follow this thread: https://community.home-assistant.io/t/swipe-for-sidebar/556909

**Comment by MauiR** [comment]
> I can no longer seem swipe right from the left edge on the Android app to get to the menus while in Kiosk Mode in release 1.8.1.

I have the same issue on iOS devices.

**Comment by elchininet** [comment]
@MauiR, please, read the links that I provided.

**Comment by MauiR** [comment]
The problem has been fixed by the iOS app update of the Home Assistant app. The issue can be closed for iOS.

**Comment by AllegedlyUndead** [comment]
@elchininet 

I thought that feature was just apart of this integration. I was not aware that the gesture was a home assistant thing!

Sorry about that I have been out of the Home assistant game for a while and went straight into kiosk mode without using the app stock!

**Comment by elchininet** [comment]
Do not worry @AllegedlyUndead, it is normal if you think that the functionality is coming from this plugin.
I think that something should be stated on the README about that but I was waiting to see if they fixed it.
Regards

**Comment by direx1** [comment]
Same issue
