### ISSUE TITLE
1.8.1 enables kiosk-mode even if not activated

### ISSUE THREAD

**Issue by DerEmder** [NemesisRE/kiosk-mode#45]
Home Assistant 2023.4.1
Supervisor 2023.04.0
Operating System 9.4
Frontend 20230406.1 - latest

I use three views: 

- **Overview** (Übersicht) for almost all entities, sensors and images.
- **Berta** exclusively for my very old Acer A210 tablet (Android 4.4).
- **Vis** as a testing ground for my html/css experiments

Kiosk-Mode is installed and enabled only with Berta. It does work nicely. Unfortunately kiosk-mode also affects the other views no matter if kiosk-mode is activated or not. So I have to use '_?disable_km=_' every time I want to edit a view other than Berta. 

The wanted effect should be to only have kiosk-mode active on Berta but not on the other views.

And yes, the little typo (missing underscore) in 'hide_sidebar' has been addressed already ;)

![Bildschirmfoto vom 2023-04-07 11-27-43](https://user-images.githubusercontent.com/91392202/230585740-e34eda3d-5c10-4c8e-b384-0d553981f746.jpg)
![Bildschirmfoto vom 2023-04-07 11-28-35](https://user-images.githubusercontent.com/91392202/230585742-e5302a4b-1e15-4c87-be15-23d6c758c76b.jpg)
![Bildschirmfoto vom 2023-04-07 11-29-15](https://user-images.githubusercontent.com/91392202/230585744-b4cbd5b3-2db4-4889-9c42-6f6ce797951d.jpg)

These yaml give the following appearance:

**Overview**

![Bildschirmfoto vom 2023-04-07 11-42-47](https://user-images.githubusercontent.com/91392202/230587531-1ce98c72-fe84-428d-abe8-8a87b33bb8ba.jpg)

**Berta**

![Tablet-hoch](https://user-images.githubusercontent.com/91392202/230587659-4852095c-e494-4fac-aa8a-cda80e8ad176.jpg)

**Vis**

![Bildschirmfoto vom 2023-04-07 11-43-44](https://user-images.githubusercontent.com/91392202/230587716-f6d746c8-105b-4729-863c-b93a7bd77fa8.jpg)

**Comment by elchininet** [comment]
Hi @DerEmder,
I‘m trying to reproduce it but I can‘t. Try something and let me know the result, disable `kiosk-mode` in Berta dashboard (delete the configuration) and check if it keeps hiding the header, I think that it could be multiple things executing there.

**Comment by DerEmder** [comment]
You are magic :)

Ok, did that, then ?clear_km_cache - now all is ok. Then activated in Berta (and only this view) again. Now all is good. That's weird because I tried these steps already, unsuccessfully I must say.

But now it worked. Thank you!
