### ISSUE TITLE
'disable_km' - only for admins 

### ISSUE THREAD

**Issue by fctpn** [NemesisRE/kiosk-mode#47]
Is there any possibility to have this option available only for the admins?

**Comment by elchininet** [comment]
Hi @fctpn,
At the moment, it is not possible. Anyone with access to the URL can disable the `kiosk-mode`. I‘ll let the issue open as a feature request.
Regards

**Comment by elchininet** [comment]
Hi @fctpn,
A new version of the library has been released, you can check [here](https://github.com/NemesisRE/kiosk-mode/pull/62) some examples of the new option.
Regards
