### ISSUE TITLE
Swipe to open stopped working

### ISSUE THREAD

**Issue by theone11** [NemesisRE/kiosk-mode#49]
I have been using this great extension for quite a long time but lately the swipe to open the sidebar has stopped working.

I have recently installed HomeAssistant 2023.04 but don't know if the rpoblem already happened before.

I have the following My Kiosk Mode configuration:

kiosk_mode:
  hide_header: true
  hide_menubutton: true
  hide_overflow: true

**Comment by Mr-HaleYa** [comment]
+1 I have also noticed this

**Comment by that1guy** [comment]
+1 Confirmed issue over here too.

**Comment by shahardot** [comment]
+1 
Running 2023.4.1 with latest kiosk-mode, set as "hide_header": "true" and swipe isn't working since the last HA upgrade.

**Comment by RobbanMurray** [comment]
+1, running HAOS 2023.4.2 and KM 1.8.1

**Comment by elchininet** [comment]
Hi @theone11,
Please, refer to [this issue](https://github.com/NemesisRE/kiosk-mode/issues/42). Before opening an issue, always check it the issue is still reproducible without using the plugin.
Regards

**Comment by theone11** [comment]
So, if I understood correctly, there is actually no way of swiping open the sidebar if I am using kiosk_mode and hiding the header bar where the menu button is located, correct?

**Comment by elchininet** [comment]
Hi @theone11,
The functionality to swipe and open the menu was removed from Home Assistant and the Apps (clients) need to implement it in their sides. This seems to be solved already on IOS but not in Android. If you remove the button to open the menu then you will not be able to access it.

**Comment by theone11** [comment]
I am using the browser to control ha on pc and raspberry pi so app will not help. Thanks.

**Comment by elchininet** [comment]
@theone11,
In any case, this is something that was removed in Home Assistant side, so it is not something coming from this plugin and is that what I was trying to communicate. If you want that feature in Home Assistant again, you need to request it in the right place.
Regards
