### ISSUE TITLE
Since HA 2023.4, View no longer fills the whole client viewport height in Kiosk Mode

### ISSUE THREAD

**Issue by jxlarrea** [NemesisRE/kiosk-mode#50]
Now there is a margin at the bottom of the dashboard's masonry view when using Kiosk Mode, causing views with background images to cut off. See screenshot below.

Without Kiosk Mode:
![1lol](https://user-images.githubusercontent.com/309902/230755785-4fc37f4d-3ebb-458b-bb31-7dd85588c9be.png)

With Kiosk Mode
![2lol](https://user-images.githubusercontent.com/309902/230755791-32f609ba-d574-4942-97f4-ac211c399ad4.png)

**Comment by Tadies** [comment]
Confirmed....same issue

**Comment by Mr-HaleYa** [comment]
@jxlarrea That's a good looking dashboard 👍 

also same, I removed my background image until this is fixed so I didn't have to see the cutoff lol.

**Comment by elchininet** [comment]
Hi @jxlarrea,
Please, check out [this issue](https://github.com/NemesisRE/kiosk-mode/issues/43). It should be solved in the next release.
Regards

**Comment by elchininet** [comment]
Hi @jxlarrea,
[A new version](https://github.com/NemesisRE/kiosk-mode/releases/tag/1.8.2) has been released. Please, test it and let me know if the issue is resolved.
Regards

**Comment by Tadies** [comment]
Ya got it almost right!!!!. Woooot
There is a tiny bit on bottom left yet....
So the height is not fully back yet   ...
Sofar way better tho!

**Comment by elchininet** [comment]
Hi @Tadies,
Please, post a screenshot to see if I can reproduce it on my side.
Regards

**Comment by Tadies** [comment]
![20230409_153118](https://user-images.githubusercontent.com/3147465/230775698-da3820ee-15b0-4d47-b8d8-3fa5a7ec269d.jpg)
There ya go....on bottom still a bit left

**Comment by elchininet** [comment]
That doesn't seem the same issue, you should have a black or white background if the height is not `100vh`, instead of a dark blue one. Could you tell me which theme are you using or how you added that background?

**Comment by Tadies** [comment]
This effects on all themes....
The one i showed is transparent blue...with an own background...
That's why its darkblue....that darkblue is the part that needs to be done yet....
On ohter themes it does exact the same but then with the theme assigned background color i assume

**Comment by elchininet** [comment]
It is better if you tell me which specific theme you are using so I can debug it, if not it is impossible to reproduce your issue. I tested it with the IOS Theme (dark / light) and this doesn't occur in my devices.

**Comment by Tadies** [comment]
Ok here is what i did first time....loaded your .js file...
And only a tiny bit needed to fix... 
Then i got the official update in hacs.. .
All went back as the topic said...a big block on bottom
Did get rid of it ( unnistalled)....rebooted and reinstalled
Issue is still same no matter what theme...even the default one has it   
No matter what i do  the bottom is still worse again...
Guess we need to wait for others now to comment
And yes i use  ios dark and light mode too...
Still the same....im total lost now
I appreciate your help tho!

**Comment by elchininet** [comment]
Hi @Tadies,
I just need to reproduce the issue on my device, and for that I need to know any theme in which it is occurring for you because I cannot reproduce it in the themes that I have installed. If you can not provide in which specific theme it occurs for you then we need to wait for someone that can provide that information to reproduce it.
Regards

**Comment by Tadies** [comment]
No wurry's brother...im sure you did fix it....
I known now why it has changed.....
The last few updates on has did change it...
So on your end ya fixed it.    Yay!
I known im not a guru.....
On all themes i got now the full screen back
Except the bottom was smaller before of all the has updates....so thank You !

**Comment by elchininet** [comment]
@Tadies,
Just a recommendation because maybe you don't know how this works. In any repo that you mention an issue and say something like "it happens in all systems" or "in all browsers" or "in all versions", it doesn't help, you need to provide information so developers can reproduce it. It is not magic, a developer needs to see the issue on their side and check what is happening to fix it. You posted one screenshot, if you give me information about what theme is that one I can reproduce it. If you say "with any theme" it is nothing.

But let's do it in the other way around because it seems that you don't want to say which theme is that for some reason. Could you select the IOS Theme (because it is the one that I have) and post an a screenshot to check how it looks on your side, so I can know which element could be showing the bar that you mentioned.

![image](https://user-images.githubusercontent.com/3728220/230779088-5435d131-ca99-4ff3-a409-02e564dbffa4.png)

**Comment by elchininet** [comment]
>Finally fixed.....it appears trough all updates the compannion app decided to alter the full screen settings
How stupid not to check that!

Perfect then. Good to know that it is working on your side. 👍🏼

**Comment by Tadies** [comment]
Thank for the last fix!...It did work....Btw i use the themes ios dark and light modeAnd noctisAswell Transparant Blue..All working fine again on kiosk mode.. It's not that i wanted not to postBut there where latley to many updates on has And i as noob did failed to check the settingsAfter the updates.   So version 1.82 did the trick fine!Kuddo's from the netherlands Verzonden vanaf mijn Galaxy

**Comment by sekonicpr** [comment]
Even with HA2023.4.1 and the latest versions in HACS, I still have the top header and bottom bar problem.  I'm not an expert I hope I can have some help.  thank you

![image](https://user-images.githubusercontent.com/40529944/230782022-aa937fe9-1051-444d-b881-f1e7f92fe2bc.jpeg)![image](https://user-images.githubusercontent.com/40529944/230782024-e0736b16-2019-43d8-a55d-af002c8a35c9.png)

**Comment by elchininet** [comment]
Hi @sekonicpr,
Do you have version `1.8.2` installed?
If that is the case, could you go to the dev tools, select the `ui-view` element and let me know if you can see `--header-height: 0px`?

![image](https://user-images.githubusercontent.com/3728220/230782376-ea8d0273-bdb4-4278-95c2-728902804479.png)

**Comment by elchininet** [comment]
Hi @sekonicpr,
Do you have version `1.8.2` installed?
If that is the case, could you go to the dev tools, select the `ui-view` element and let me know if you can see `--header-height: 0px`?

![image](https://user-images.githubusercontent.com/3728220/230782376-ea8d0273-bdb4-4278-95c2-728902804479.png)

**Comment by sekonicpr** [comment]
Yes, I have 1.8.2 installed, sorry I'm trying to find ui-view in the developer tools but I'm really lost.  Can you give me the steps and sorry for the inconvenience.

**Comment by sekonicpr** [comment]
ok i think i found it! --header-height: 0px

![image](https://user-images.githubusercontent.com/40529944/230783997-75b8db92-e2d8-4f44-9d6b-5e32da2447c1.jpeg)

**Comment by elchininet** [comment]
Hi @sekonicpr,
That is the `sources` tab and for the JavaScript code it seems that you are loading the correct version but I just want to check if the styles are applied to the element, you need to go to the `elements` tab and start to open the elements until you reach the `hui-view` one (right clicking on your screen and selecting `inspect` could save you some steps).

<img width="991" alt="image" src="https://user-images.githubusercontent.com/3728220/230788001-b8844f65-8e5b-4009-bc4b-bdd7c3decc9a.png">

**Comment by jxlarrea** [comment]
> Hi @jxlarrea, [A new version](https://github.com/NemesisRE/kiosk-mode/releases/tag/1.8.2) has been released. Please, test it and let me know if the issue is resolved. Regards

Works for me! Thanks!

**Comment by elchininet** [comment]
Thanks for the update @jxlarrea!

**Comment by sekonicpr** [comment]
Thanks for the help I got it.


![image](https://user-images.githubusercontent.com/40529944/230789530-7ecc53e2-7fcf-416e-83c8-73662be1bc80.jpeg)

**Comment by elchininet** [comment]
@sekonicpr,
Perfect, check at the right the styles and give me an screenshot, I need to check if you are getting the right styles.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/3728220/230791820-f391f092-9bca-49dd-976a-73afd8a2efa5.png">

**Comment by sekonicpr** [comment]
Styles screenshot

![image](https://user-images.githubusercontent.com/40529944/230792303-807cb4aa-d98d-4e1d-98b8-da22bb83ffa7.jpeg)

**Comment by elchininet** [comment]
Hi @sekonicpr,
As I supected, the styles are not applied in your case, now we need to figure it out the why.
Please, open an issue with these details, let's try to follow up this there.
Regards
