### ISSUE TITLE
One-pixel vertical line on the left side

### ISSUE THREAD

**Issue by uspino2** [NemesisRE/kiosk-mode#54]
Hello. Ever since the latest updates (errors corrected - thanks!) I now get a one-pixel white vertical line on the left side in full kiosk mode. Looks like the sidebar is not entirely hidden. Tried in Safari, Chrome, Mobi Kiosk, etc., and the line is always there. It was never there in the last few months (years?). Installation is HACS, calling kiosk mode by adding _?kiosk_ at end od dashboard address. Any help? Thanks.

![Screenshot 2023-04-10 at 8 25 22 AM](https://user-images.githubusercontent.com/24617436/230841271-ae6887f2-4bd0-4013-b029-5ba405d05719.png)

**Comment by elchininet** [comment]
Hi @uspino2,
Please, refer to [this issue](https://github.com/NemesisRE/kiosk-mode/issues/33). The sidebar is completely hidden with `display: none` if you use `hide_sidebar`.
Regards

**Comment by elchininet** [comment]
Just as a reference, this is how `kiosk-mode` looks on my side: 

![image](https://user-images.githubusercontent.com/3728220/230893898-abac0abe-3538-4356-b2fe-3dffff633410.png)

**Comment by elchininet** [comment]
Hi @uspino2,
I have noticed what you are referring setting the theme in light mode (in dark mode the line is black). The line is coming from Home Assistant, it was introduced in `2023.4` and it is present all the time between the lovelace panel and the sidebar, but if the sidebar is hidden the line remains there. I‘ll reopen your issue, we need to check if it is possible to remove that with styles.
Regards

| With sidebar | Without sidebar |
| ------------- | ---------------- |
| ![image](https://user-images.githubusercontent.com/3728220/230960125-5a69099e-b9c2-4520-9760-12d363ded8fc.png) | ![image](https://user-images.githubusercontent.com/3728220/230960208-f4b46d3a-738e-48a4-9329-ca8f955be2af.png) |

**Comment by elchininet** [comment]
I‘ve discovered the annoying element. It shoulf be easy to hide it when the sidebar is hidden. In my case, using the IOS Theme with dark mode that line is dark, you can enlarge my screenshot above, it is hard to see because it has almost the same background color, but it is there.

![image](https://user-images.githubusercontent.com/3728220/230961576-eb27af99-931f-4fc8-9e7e-adc4dc821443.png)

**Comment by elchininet** [comment]
Hi @uspino2,
When this gets merged and a new version is released, your issue should be solved: https://github.com/NemesisRE/kiosk-mode/pull/56
Regards

**Comment by uspino2** [comment]
> Hi @uspino2,
> A new version has been released. Please, test it and check if the issue is resolved for you.
> Regards

Fixed! Thank you so much!
