### ISSUE TITLE
not working since last update

### ISSUE THREAD

**Issue by ultimendum** [NemesisRE/kiosk-mode#55]
installed last update just now and kiosk mode stopped with error in logs:

Logger: frontend.js.latest.202304061
Source: components/system_log/__init__.py:257 
First occurred: 09:43:54 (13 occurrences) 
Last logged: 09:56:44

http://ip_addr:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:1:5301 TypeError: null is not an object (evaluating 'i.querySelector')
http://ip_addr:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:1:5206 TypeError: null is not an object (evaluating 'e.shadowRoot.querySelector("hui-root").shadowRoot')

am i doing something wrong?

**Comment by elchininet** [comment]
Hi @ultimendum,
Your browser or device is loading the old version. Please, try to clean you cache.
Regards

**Comment by elchininet** [comment]
Hi @ultimendum,
Were you able to solve the issue?

**Comment by hugostegeman** [comment]
For me its working again but only on webpages.
The Android app is not working.

**Comment by hugostegeman** [comment]
@elchininet 

Thanks for the reply.
The problem was that my kiosk mode swith was off.

**Comment by elchininet** [comment]
@hugostegeman, good to know that it is solved 👍🏼

**Comment by elchininet** [comment]
Hi @hugostegeman,
It seems that you already solved your issue or are not interested on it anymore.
Closing this issue.
Regards
