### ISSUE TITLE
Mobile App Settings Android 2023.3.0-full

### ISSUE THREAD

**Issue by Quotenjunkie** [NemesisRE/kiosk-mode#59]
Hi,

since the app version mentioned above, I do not get kiosk mode to work correctly on any mobile device.
No matter which option I choose the sidebar will also be hidden.

kiosk_mode:
  mobile_settings:
    hide_header: true

BR

**Comment by elchininet** [comment]
Hi @Quotenjunkie,

Describe better your issue. What exactly do you mean with "hidden"?. Depending on the device size the sidebar is always hidden and this is not something coming from `kiosk-mode`, it is how it is designed.

If you mean that you cannot open the sidebar with a swipe gesture, please, check this issue: https://github.com/NemesisRE/kiosk-mode/issues/42

Regards

**Comment by direx1** [comment]
Same issue. Unable to swipe sidebar out using latest android. Even tried the beta version as apparently not an issue using hide_sidebar using ios

**Comment by elchininet** [comment]
Hi @direx1,

Please, consult this issue: https://github.com/NemesisRE/kiosk-mode/issues/42

**Comment by Quotenjunkie** [comment]
> Hi @direx1,
> 
> Please, consult this issue: https://github.com/NemesisRE/kiosk-mode/issues/42

Thank you very much for this hint!

BR
