### ISSUE TITLE
Uncaught TypeError via ?kiosk

### ISSUE THREAD

**Issue by chicknlil** [NemesisRE/kiosk-mode#67]
Hello!

I've had an issue that started with the maykar version of kiosk-mode and still persists through yours:

```
Logger: frontend.js.latest.202305033
Source: components/system_log/__init__.py:257
First occurred: May 5, 2023 at 10:03:39 PM (44 occurrences)
Last logged: 1:34:26 AM

http://192.168.1.84:8123/lovelace/front-door-tablet-dash?kiosk:0:0 Uncaught
http://192.168.1.84:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128183:1:19720 Uncaught TypeError: Cannot read property 'dataset' of null
http://192.168.1.84:8123/lovelace/kitchen-cast?kiosk:0:0 Uncaught
http://192.168.1.84:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128183:1:19720 Uncaught TypeError: Cannot read properties of null (reading 'dataset')
http://192.168.1.84:8123/lovelace/kiosk?kiosk:0:0 Uncaught
```

Point of reference: I use kiosk mode on 2 wall-mounted fire tablets and 2 google hubs. The hubs utilize [DashCast](https://github.com/AlexxIT/DashCast), while the tablets run [Fully-Kiosk](https://www.fully-kiosk.com/en/#download-box).  As you can see, despite the different devices, this continues to appear.

It appears to be a similar but not identical issue to #1 in that it "Cannot read property 'dataset' of null".

Happy to supply any additional information you might need!

**Comment by elchininet** [comment]
Hi @chicknlil,
Please, refer to [this closed issue] (https://github.com/NemesisRE/kiosk-mode/issues/66), it is a clone of yours).
Regards

**Comment by chicknlil** [comment]
My bad, I didn't see that because it was closed.

**Comment by chicknlil** [comment]
That did the trick for me - thank you so much!
