### ISSUE TITLE
Add Arbitrary Button To Header  (feature request)

### ISSUE THREAD

**Issue by efaden** [NemesisRE/kiosk-mode#69]
Would be cool to be able to add an arbitrary button/menu to the action items to load a browser mod style popup. Use case would be to have a menu/button that is present on all of my tablets.

**Comment by elchininet** [comment]
Hi @efaden,
That unfortunately falls out of the scope of this plugin. This plugin is intended for hiding elements from the screen to make Home Assistant compatible with a Kiosk device in which it should not be allowed to interact with some elements. Being able to add new elements to perform custom tasks is something not related to `kiosk-mode`, I would recommend you to explore [sidebar-card](https://github.com/DBuit/sidebar-card) and check if such functionality could be added there.
Regards

**Comment by efaden** [comment]
No worries. Thanks!
