### ISSUE TITLE
Sidebar not accessible

### ISSUE THREAD

**Issue by lunatik98** [NemesisRE/kiosk-mode#71]
Hi,

since a few weeks ago Kiosk Mode hides my sidebar and I cant swipe to open it :(

I didnt change my settings and they look like this:

kiosk_mode:
  mobile_settings:
    hide_header: true
    hide_sidebar: false

Any idea whats wrong?

**Comment by elchininet** [comment]
Please, @lunatik98,
Check this closed issue that is a clone of yours: https://github.com/NemesisRE/kiosk-mode/issues/42
Also good that you follow this thread: https://community.home-assistant.io/t/swipe-for-sidebar/556909/22
Regards
