### ISSUE TITLE
Just show assist/conversation icon?

### ISSUE THREAD

**Issue by dnestico** [NemesisRE/kiosk-mode#74]
Hi, I disabled everything in the menu/overflow menu thinking that would replace the 3 dots with just the assist icon, but it didn't. Would like to know if it's possible to just show the assist icon instead of the 3 dot icons on mobile, thanks.

![Screenshot_20230521-183733](https://github.com/NemesisRE/kiosk-mode/assets/3034555/ffb2cd31-c20a-4171-9067-f9d1003dffbb)

**Comment by elchininet** [comment]
Hi @dnestico,
That falls out of the scope of `kiosk-mode`. The purpose of this plugin is just to **hide** certain elements from the screen to be able to display Home Assistant as a kiosk in which users are not allowed to interact with these elements. Replacing elements is something that you would need to implement with other plugins/techniques.
Regards
