### ISSUE TITLE
Headsup next HA release will break kiosk mode

### ISSUE THREAD

**Issue by tbrasser** [NemesisRE/kiosk-mode#76]
Yet to investigate what changed this time but the beta is dropping today and the latest dev shows the header even though it's hidden via kiosk mode.

**Comment by elchininet** [comment]
Thanks for the heads up @tbrasser,
I‘ll check what have changed and apply the proper changes.
Regards

**Comment by elchininet** [comment]
Hi @tbrasser,
No worries, it fails because the development tag is `2023.6.0.dev20230531`, it will not fail when the tag is `2023.6.x`. But I‘ll push a fix to avoid an error with development tags.
Regards

**Comment by elchininet** [comment]
@tbrasser, [pull request created](https://github.com/NemesisRE/kiosk-mode/pull/77), when it gets merged, and a new version is released, `kiosk-mode` will not fail with Home Assistant develpment tags.
Regards

**Comment by elchininet** [comment]
Hi @tbrasser,
[A new version](https://github.com/NemesisRE/kiosk-mode/releases/tag/v1.9.1) has been released. Test it and let me know if it works well with the latest Home Assistant development tag.
Regards

**Comment by tbrasser** [comment]
I tried 1.9.1 but didn't see it work. Have updated in the meantime to the beta, and of course now kiosk mode is working again. So indeed correct triage.

**Comment by elchininet** [comment]
Hi @tbrasser, could you explain this part?

>I tried 1.9.1 but didn't see it work.

I have the version `1.9.1` in my instalation (`2023.5.4`) and it is working properly, could you tell me in which version it doesn‘t work?

Regards

**Comment by tbrasser** [comment]
Didn't work on the dev version but working beautifully on the beta

**Comment by elchininet** [comment]
Could you tell me wich dev version you were trying? I have tested it with `2023.6.0.dev20230531`.
