### ISSUE TITLE
Kiosk mode completely non functional

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#78]
and tbh, I am not sure if the current beta 2023.6 causes it, or the last update to Kiosk-mode..

in any case, we need to check ;-)

<img width="503" alt="Scherm­afbeelding 2023-06-01 om 07 48 43" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/ea54da8f-4474-4a46-9696-ba9915853a24">

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
That is what is being trying to solve [here] (https://github.com/NemesisRE/kiosk-mode/issues/75). Please, test the gist and let me know.
Regards

**Comment by Mariusthvdb** [comment]
right.... I didnt realize... and figured last release would have incorporated all you had done.

and yes, that gist brings it all back.. cool

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
The last release only included a small change not related to this (https://github.com/NemesisRE/kiosk-mode/pull/77). Good to know that the code in the gist fixes the error, but before creating a pull request, could you check that the options to hide the items inside the sidebar menu are working too?
Regards

**Comment by Mariusthvdb** [comment]
sure, I already did that ;-)

all of my toggles are functional 

only thing I feel that should still be addressed is that when all items are disable, the whole spot in the menubar is deleted. I still need my template there to be functional in that case.

other than that, its a go in my opinion

**Comment by elchininet** [comment]
Perfect, I'll proceed then. I remember that you talked about that before, that could be achieved with another option just for your use case, please, create another issue describing that, I'll work on it when I have a chance.
Regards

**Comment by elchininet** [comment]
Let's cover this topic in the original issue. Closing this one.

**Comment by Mariusthvdb** [comment]
sure, what ever makes this repo swing.
though this really was no duplicate of the other issue, as that didnt break Kiosk Mode

Thanks!

**Comment by elchininet** [comment]
It is a dupe because it is the same error and located in the same logic in the code, if the solution to fix the error is the same it doesn't matter if it produces different outcomes for different users/environments.
