### ISSUE TITLE
URL-parameter settings don't work on energy dashboard

### ISSUE THREAD

**Issue by alsFC** [NemesisRE/kiosk-mode#8]
Unfortunately the URL-parameter settings don't have any effect when passing to the built-in energy dashboard.

**Comment by elchininet** [comment]
Hi @alsFC,
At the moment, this plugin only works with Lovelace dashboards, other dashboard are not supported. Maybe this is something to state in the README of the repo.
Regards.

**Comment by elchininet** [comment]
It has been stated on the README that this library

>Hides the header and/or sidebar drawer in Home Assistant **lovelace dashboards**

Closing this issue.
