### ISSUE TITLE
[BUG] After HA Core 2023.6.0, Hide Header not working

### ISSUE THREAD

**Issue by limitless00net** [NemesisRE/kiosk-mode#88]
**Describe the bug**
After HA Core 2023.6.0, Hide Header not working

**Versions:**
 - Home Assistant: Core 2023.6.0
 - Kiosk-Mode v1.9.3

**Comment by elchininet** [comment]
Hi @limitless00net,
Please, let us know which browser you are using and also if you have some JavaScript errors in the console, I am also using `2023.6.0` without any issues.
Regards

**Comment by elchininet** [comment]
@tbrasser, @Mariusthvdb, could you guys confirm if you are having any issues after the upgrade to `2023.6.0`?

**Comment by tbrasser** [comment]
Seems flakey since 1.9.x, but unsure if race condition or frontend cache issue. After refreshing the page a couple of times I finally get a hidden header, but it's not consistent.

**Comment by elchininet** [comment]
Good to know it @tbrasser could you tell me if there are any errors in your logs?

**Comment by limitless00net** [comment]
> Hi @limitless00net, Please, let us know which browser you are using and also if you have some JavaScript errors in the console, I am also using `2023.6.0` without any issues. Regards

it's not consistent for me too.

Chrome 114.0.5735.110 (64bit)

kiosk-mode.js?hacstag=497319128193:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'shadowRoot')
    at new t (kiosk-mode.js?hacstag=497319128193:1:11451)
    at kiosk-mode.js?hacstag=497319128193:1:23001

**Comment by elchininet** [comment]
Could you guys, try to manually install [the code in this gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) and check if the issue still happens there? 

To install the library manually, please, uninstall it from HACS and follow the instructions in [the README](https://github.com/NemesisRE/kiosk-mode#installation).

**Comment by elchininet** [comment]
The gist should not solve the issue for you. Looking at the column `11451`, it is failing trying to select `home-assistant-main`, it is not present for you in the moment that the code is executed and this is a core element for the library because it contains the rest of the elements. I don‘t know why this element is not available for you during first rendering but I assume that moving all these selectors to promises could fix the issue. I‘ll try to do some changes on top of [these ones](https://github.com/NemesisRE/kiosk-mode/pull/87) and submit a pull request.

**Comment by elchininet** [comment]
Thanks for the report @Mariusthvdb, I don‘t have issues either but it seems that in certain conditions that I cannot reproduce, the main Home Assistant element is not present when `kiosk-mode` is executed. I‘ll work in a pull request that should fix it.

**Comment by elchininet** [comment]
Hi @limitless00net, cc: @tbrasser,
Just a reminder that [this pull request](https://github.com/NemesisRE/kiosk-mode/pull/89) is waiting for your tests. As the issue is only happening on your side, it is important that you test these changes and report back if they solve the issue.
Regards

**Comment by tbrasser** [comment]
Sorry, wasn't home for a few days. Just tried it and I haven't seen the header appear since. Seems solid!

**Comment by elchininet** [comment]
Those are great news @tbrasser, please use that bundle until a new version is released. @limitless00net could you test it too on your side?
Regards

**Comment by limitless00net** [comment]
> Could you guys, try to manually install [the code in this gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) and check if the issue still happens there?

Hide Header seems to work in this code in this gist. Thanks!
I hope a new version will be released soon.

**Comment by elchininet** [comment]
Hi @limitless00net,
Thanks for the update, please, use the gist code until a new version is released. I‘ll let you know when it is released.
Regards

**Comment by elchininet** [comment]
Hi @limitless00net, cc: @tbrasser,
[A new version has been released](https://github.com/NemesisRE/kiosk-mode/releases/tag/v1.9.4). You can remove the manual install and install this version through HACS again.
Regards
