### ISSUE TITLE
[FR] Option to make background transparent

### ISSUE THREAD

**Issue by maltejur** [NemesisRE/kiosk-mode#90]
**Is your feature request related to a problem? Please describe.**

I want to add home assistant as a widget to my desktop. If there was an option to make the background transparent, it would feel much more integrated.

**Describe the solution you'd like**

Add the option `transparent_background`, which applies the following CSS:

```css
html {
  background-color: transparent;
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by NemesisRE** [comment]
I am not sure if this is in the scope of kiosk-mode

**Comment by elchininet** [comment]
Hi @maltejur,
Same comment as @NemesisRE. This plugin is intended to hide elements from the screen and in this way be able to run home assistant in a device intended to be used as a kiosk device in which non-authorized users are not able to interact with them. It is not intended to change theme variables. What you are searching can be achieved with a [custom theme](https://www.home-assistant.io/integrations/frontend/#defining-themes) and specifically the variable that you need to change is `primary-background-color`.
Regards

**Comment by maltejur** [comment]
Ah ok, I wasn't 100% sure myself if this would be appropriate for this repo, thanks for your response!
