### ISSUE TITLE
[BUG]  ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#95]
**Describe the bug**

**To Reproduce**
1. enable kiosk-mode
2. disable kiosk-mode
3. check inspector
4. 

**Expected behavior**
NO ResizeObserver loop completed with undelivered notifications. in Inspector
**Screenshots**
<img width="422" alt="Scherm­afbeelding 2023-06-19 om 14 07 31" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/a2b8487e-0c6e-4625-8ad3-d31aad16b420">

**Versions:**
 - Home Assistant: 2023.6.2
 - Kiosk-Mode 2.0.0 (currently with new test gist on dialog items

**Additional context**

this has been a long standing HA warning/error in the logs, and never was able to pinpoint it. testing Kiosk mode now, made this 100% reproducible

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
Is that happening with the version published in HACS too?
Regards

**Comment by elchininet** [comment]
Maybe related to this: https://community.home-assistant.io/t/0-resizeobserver-loop-completed-with-undelivered-notifications/322338

I am seeing that it is not an error coming from `kiosk-mode` but as `kiosk-mode` changes the layout and triggers a resize even maybe it triggers the issue.

**Comment by elchininet** [comment]
The loop comes to you :)

https://github.com/home-assistant/frontend/issues/9022#issuecomment-1401117599

**Comment by Mariusthvdb** [comment]
haha, yes, ive filed that before, and even figured Kiosk-mode was connected. COuldnt make that happen for a while though, and didnt checkmate after wards. 
The release version doesnt seem to do that, I need to re-check.

**Comment by elchininet** [comment]
>downgraded to release 2.0.0 and the ResizeObserverLoop is no longer showing
Good to know, anyway the work in progress code doesn‘t have anything related to that, this should be happening any time that the window is resized so the `ResizeObserver` code runs.

**Comment by Mariusthvdb** [comment]
yes, it does happen when resizing the window, even on the release version.

its really odd to **not** see it using release version on Disabling kiosk mode at all, and seeing it on **every** Disable when using the new Gist version

**Comment by elchininet** [comment]
>its really odd to not see it using release version on Disabling kiosk mode at all, and seeing it on every Disable when using the new Gist version

Maybe because the guist executes the window resize in a different order, I need to check. But anyway, the response to that error [is just to ignore it](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded) (but it would be good to know how to remove it fro your logs, or if it should be ignored convince HA Frontend guys to remove it from the logger).

**Comment by elchininet** [comment]
>disabling Kioks-mode causes the window to resize, and next the error os thrown?

Enabling or disabling `kiosk-mode` makes the layout to change so a `ResizeOversever` could be triggerd and when one enables `kiosk-mode` a `window.dispatchEvent(new Event('resize'));` is called, so it can trigger it too.

**Comment by elchininet** [comment]
@Mariusthvdb,
By the way, I didn‘t read carefully [the block of code](https://github.com/home-assistant/frontend/blame/7c15a65bba8a9dc1c9406a2026cd466a8a03a1ee/src/entrypoints/core.ts#L136-L147) before. The commit is form yesterday and basically what it does is to stop the propagation of those errors (now including also "ResizeObserver loop completed with undelivered notifications") so they are not going to be logged in the logs.

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
[The fix is already on Frontend 20230705.1](https://github.com/home-assistant/frontend/commit/7c15a65bba8a9dc1c9406a2026cd466a8a03a1ee). You should not see that message anymore. It would be good to update other folks [here](https://github.com/home-assistant/frontend/issues/9022).
Regards
