### ISSUE TITLE
[BUG] KioskMode seems not to work with HA 2023.6.2

### ISSUE THREAD

**Issue by modem** [NemesisRE/kiosk-mode#96]
**Describe the bug**
Have the following config, though the search icon still appears for non admin users. Tested also to hide the header but the header still shows.
```kiosk_mode:
  non_admin_settings:
    hide_header: false
    hide_search: true
```
I noticed this issue, closed last week, I was expecting it to work, but it seems it does not work for me: https://github.com/NemesisRE/kiosk-mode/issues/88

I see on errors on the browser (Firefox).

UPDATE: also tested with the latest version of Google Chrome and it does not work as well. There's also no error in the console related to this addon.

**Versions:**
 - Home Assistant: 2023.6.2
 - Kiosk-Mode: v2.0.0

**Comment by elchininet** [comment]
Hi @modem,
I have tested the `non_admin_settings` and it works perfect on my side.
Are you placing your config under the `kiosk_mode` config?
Regards

**Comment by modem** [comment]
Yes, at the top of the dashboad
![image](https://github.com/NemesisRE/kiosk-mode/assets/62859/93b0b1c4-2b7a-4a45-a63c-1b1d01491a66)

**Comment by elchininet** [comment]
Do you see this on your console?

<img width="246" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/3728220/0a4edce3-014b-4974-8d96-df89f05dff1b">

**Comment by modem** [comment]
I do. This is everything I have, there are 2 errors that don't seem related to this, and a warning related to another card
![image](https://github.com/NemesisRE/kiosk-mode/assets/62859/28a70aba-96f0-4b35-a8d9-34ca5b411a47)

Is there anything I can test?

**Comment by elchininet** [comment]
Perfect, that is a good sign, at least the code is executing.
Let‘s try a few options before debugging your layout. Could you add `?clear_km_cache` to the URL and execute just to be sure that you don‘t have any settings cached?

**Comment by modem** [comment]
Same result with the `?clear_km_cache` parameter. I also tried several times with CTRL+F5 to force the reload without cache

This is the end of my URL (now with the `?clear_km_cache`)
![image](https://github.com/NemesisRE/kiosk-mode/assets/62859/bd0f0e2b-5070-4d2f-831f-8c218f8f781a)

**Comment by elchininet** [comment]
Was `kiosk-mode` working for you before?
Other options work for you or only the `non_admin_settings`?
Try with 

```yaml
kiosk_mode:
    hide_header: true
```

And check if it hides the header.

**Comment by modem** [comment]
Yes, it was working before, but I don't remember the working versions as I does not impact my account.

I just tried with the hide_header but the header still shows.

Is there a way to use a previous version to check if it starts working again?

**Comment by elchininet** [comment]
>I just tried with the hide_header but the header still shows.

Then it is not related to `non_admin_settings`, it is just that the library is not executing.

>Is there a way to use a previous version to check if it starts working again?

You can download the version thst you want to test [from the releases](https://github.com/NemesisRE/kiosk-mode/releases) and [install it manually](https://github.com/NemesisRE/kiosk-mode#installation).

**Comment by modem** [comment]
I don't know what I did, but the addon disappeared from my installation. I guess I clicked the Uninstall but I don't remember...
I re-installed it again and all of the sudden it started to work.
I wonder why the re-download did not work as well.

**Comment by elchininet** [comment]
Good to her that it is working for you.
I really don‘t know what could happen, but good to know that it is working again.
Regards

**Comment by modem** [comment]
Thanks for the near-real-time support!

**Comment by elchininet** [comment]
Welcome!
