### ISSUE TITLE
[FR] ha-tabs center

### ISSUE THREAD

**Issue by toughvj** [NemesisRE/kiosk-mode#97]
Hi, is it possible to add functionality to center items in ha-tabs when the sidebar is hidden?

**Comment by elchininet** [comment]
Hi @toughvj,
This plugin is intended just to hide elements from Home Assistant to be able to run it in a kiosk-device, and in this way being able to hide sensible functionalities from non-authorized users that can interact with these devices. It is not intended to change the style or the apparence of elements in any way. I recommend you to explore [card-mod](https://github.com/thomasloven/lovelace-card-mod), that plugin is specifically to achieve customizations like the one that you are looking for.
Regards

**Comment by elchininet** [comment]
Hi @toughvj,
A new section has been added to [the kiosk-mode complements documentation](https://github.com/NemesisRE/kiosk-mode/blob/master/KIOSK-MODE-COMPLEMENTS.md#align-header-tabs-to-the-center) showing how to center the header tabs.
Regards
